### ISSUE TITLE
Ignore "//" comments in package.json browserify.transform

### ISSUE THREAD

**Issue by hackel** [babel/babelify#104]
NodeJS ignores "//" keys in the package.json file as comments.  (See https://groups.google.com/d/msg/nodejs/NmL7jdeuw0M/yTqI05DRQrIJ)  I discovered today that if such a comment is included in the babelify options, it crashes. E.g.:
```json
{"browserify": {
    "transform": [["babelify", {
                "//": "This crashes Babelify",
                "stage": 2,
                "compact": false
    }]]
}}
```

This produces the following error:
```
ERROR [framework.browserify]: bundle error
ERROR [framework.browserify]: ReferenceError: [BABEL] any-unrelated-file.js: Unknown option: direct.// while parsing file: any-unrelated-file.js
```
It took me ages to track down this problem, so I wanted to make sure others know about it.  Looks like it could be avoided by explicitly checking for and ignoring 'direct.//'.  Also, the error message could be more explicit about where the error occurs, that it's in the Babel options, not the actual source file.

**Comment by zertosh** [comment]
Interesting. The package.json parsing is handled by browserify, and the options interpreting is handled by babel. I'm also a collaborator on browserify, and I can tell you that if you start filtering keys there, you're just asking for trouble. I don't know if @sebmck would want to filter those while babel is reading the options.

FYI: if you use a babelrc file, you can use actual js comments and those will get cleaned out before the JSON parsing.

**Comment by sebmck** [comment]
Yeah I dunno if it make senses to filter those options. Seems like more pain and it doesn't make sense to be so lenient.

**Comment by zertosh** [comment]
I agree with @sebmck. I just ran a quick test with npm. If you have `"dependencies": {"//": "comment"}` in a package.json, it'll crap out looking for a `/@comment` package. So we're not alone in not skipping `//`.

**Comment by hackel** [comment]
For some reason I didn't realize you could use .babelrc with babelify, too.  I really prefer that to package.json.
