### ISSUE TITLE
this is undefined with babelify/polyfill

### ISSUE THREAD

**Issue by Globegitter** [babel/babelify#106]
I am using https://github.com/caleb/broccoli-fast-browserify to build my js app and everything works fine until I add the polyfiill via `browserify.add(require.resolve('babelify/polyfill'))`. 

It adds the polyfill just fine, I can see it in the resulting code but the problem is with the following library on the following line:  https://github.com/MikeMcl/decimal.js/blob/aaa0794f69cf8cde935048bc75ef9c45097d03b4/decimal.js#L4060

Once I add the polyfill that line turns into `})(undefined);`. Without it it stays as expected: `})(this);`. Not sure if that is an issue with browserify or babelify or this polyfill.

When I add a custom file `browserify.add(require.resolve('./test'))` which just has a `console.log` all works as expected.

 Still going to invest on this but wanted to report it in the meantime.

**Comment by zertosh** [comment]
What you're seeing the [strict](http://babeljs.io/docs/advanced/transformers/other/strict/) transform in action. You seem to imply that not adding the polyfill makes it work? I don't know why that would be the case. Also, you probably shouldn't be applying babel to modules. Can you give me a repo with a minimal repro case that I use to debug the issue?

**Comment by jeromecovington** [comment]
I'm seeing the same issue here with the usage of some of my front end library dependencies. What is the proper usage of babelify in regards to front end modules without replacing `this` with `undefined`? What is safe to send through babelify? Can you please clarify? In my case I am using the babelify browserify transform.

**Comment by zertosh** [comment]
@jeromecovington You shouldn't be bebelifying external dependencies. You're probably running babelify as a global transform
