### ISSUE TITLE
Update to Browserify 11

### ISSUE THREAD

**Issue by gionkunz** [babel/babelify#108]
Hey there! Thanks for this transform. Any chance you could publish a new major that updates to browserify 11?

**Comment by jmm** [comment]
@gionkunz I'm not quite sure what you mean. `babelify` only specifies `browserify` in `devDependencies`. If you're just using it you have to bring your own `browserify`, and if you're hacking on it you can change the dev dep version yourself. Or are you saying it's not compatible with `browserify@11` somehow?

**Comment by gionkunz** [comment]
My bad, it wasn't babelify that's not compatible with Browerify 11 but an issue with browserify-shim and Browserify 11. I'll close the issue and sorry for being so trigger happy ;-)

**Comment by jmm** [comment]
Ok, don't worry about it :)
