### ISSUE TITLE
Experimental options doesn't work in React app.

### ISSUE THREAD

**Issue by maratfakhreev** [babel/babelify#109]
Hi, I have some problems with experimental options for babelify. I'm trying to use `stage: 0` features in React app, but it brokes (same behavior with the `optional: ['es7.classProperties']`). The error:

![screen shot 2015-08-18 at 10 53 01](https://cloud.githubusercontent.com/assets/1300497/9324980/b56c9ae8-4597-11e5-971e-d60b5329e803.png)

My browserify config:

```javascript
var gulp = require('gulp');
var rename = require('gulp-rename');
var browserify = require('browserify');
var transform = require('vinyl-transform');
var babelify = require('babelify');
var watchify = require('watchify');
var notify = require('gulp-notify');
var config = require('../config');
var entryPoint = './' + config.appDir + '/scripts/application.jsx';

gulp.task('browserify', function() {
  var bundler = browserify({
    cache: {},
    packageCache: {},
    fullPaths: true,
    debug: true,
    entries: entryPoint,
    extensions: ['.jsx'],
    paths: ['./' + config.appDir]
  })
  .transform(babelify.configure({
    stage: 0
  }));

  function bundle() {
    var bundleTransform = transform(function(filename) {
      return bundler.bundle();
    });

    return gulp.src(entryPoint)
      .pipe(bundleTransform)
      .on('error', notify.onError())
      .pipe(rename('application.js'))
      .pipe(gulp.dest(config.publicDir))
  };

  watchify(bundler).on('update', bundle);

  return bundle();
});
```

**Comment by zertosh** [comment]
works for me. can you provide me with a way to reproduce the issue? (like a minimal repo that highlights the problem)

**Comment by maratfakhreev** [comment]
I just start the gulp and this error occurs. If I remove `{ stage: 0 }` from `babelify.configure` all works fine

**Comment by zertosh** [comment]
But like I said, it works for me. Adding `{ stage: 0 }` works. Have you confirmed that you're using the latest versions?

**Comment by maratfakhreev** [comment]
@zertosh Yeah, that were dependencies conflicts and not the fresh version. All has fixed
