### ISSUE TITLE
[Feature-Request] Babel object reuse

### ISSUE THREAD

**Issue by dcbrwn** [babel/babelify#114]
Can you add unwrapped babel object to babelify? Something like babelify.babel. I have both client and server code in es6, and forced to install both babel and babelify which is a bit clumsy.

**Comment by zertosh** [comment]
This would create more confusion. If you *really* want the `babel` in `babelify`'s `node_modules` dir, you can `require` it yourself.

**Comment by stylemistake** [comment]
Why `babel` isn't in `peerDependencies`? This would solve the issue, and also saves space in case you use both. Putting babel inside babelify just doesn't make sense. Correct me if I'm wrong.

**Comment by jmm** [comment]
With `npm@3` `peerDependencies` aren't going to be installed automatically anyway. If you want both `babel-core` and `babelify` (with same `babel-core`) then I'm thinking you probably should be explicitly depending on `babel-core`, and if it's compatible with your `babelify` dep then `babelify` should get the same top-level `babel-core`.

**Comment by zertosh** [comment]
Exactly what @jmm said. Keep in mind that babelify has babel-core at `^5.0.0` - that's a pretty flexible range, it should dedupe for you.

**Comment by dcbrwn** [comment]
Actually this isn't just babelify problem. I guess all transform plugins suffered from same issue like this one. Maybe browserify has some kind of 'server-mode'? Or maybe there is workaround?

**Comment by zertosh** [comment]
You can always `require` the built bundle server side. In node, the `require` call is synchronous, while the entire browserify transform pipeline is built on async streams. So, I don't think you'd get very far trying to use the same browserify transform, to transform server-side require calls.

**Comment by dcbrwn** [comment]
I've tried to just bundle server code with browserify, but there is two main issues i got at least for now:
- if insertGlobals: true then process, events, etc. gets screwed up
- if insertGlobals: false then __filename and __dirname gets screwed up

i agreed that it's not a big deal to just avoid using __dirname/filename. But maybe there is more issues.

**Comment by zertosh** [comment]
You can pass the following to browserify so it doesn't insert `process`, `buffer` and `global`, but still gives you `__filename` and `__dirname`:

```js
browserify({
  insertGlobalVars: {
    process: undefined,
    buffer: undefined,
    global: undefined
  }
});
```

Or `builtins: false` so that core modules don't get replaced.
