### ISSUE TITLE
array comprehension Error

### ISSUE THREAD

**Issue by chenkehxx** [babel/babelify#115]
my code is 
`var a1 = [1, 2, 3, 4];
var a2 = [for (i of a1) i * 2];`
when it transform, I got the log
`gulp-notify: [Compile Error] SyntaxError: /Users/chenke/Documents/source/github/gulp-tools/app/scripts/app.js: Unexpected token (45:10) while parsing file: /Users/chenke/Documents/source/github/gulp-tools/app/scripts/app.js`
what is wrong, what should I do?

**Comment by zertosh** [comment]
Comprehensions are an [experimental](http://babeljs.io/docs/usage/experimental/) transform. You either need to set `stage` to `0`, or explicitly add it via `{ optional: ["es7.comprehensions"] }`.
