### ISSUE TITLE
Show an example with watchify

### ISSUE THREAD

**Issue by ngryman** [babel/babelify#116]
Hey,

Related to #64, I've experienced really slow incremental builds with `babelify`, until I discovered I was doing it wrong.

Thanks to this [stackoverflow answer], I realized that I was applying transform on `watchify` instead of `browserify`. I guess I'm not the only one doing this mistake, so it would be nice that the docs mention it somehow.

[stackoverflow answer]: https://stackoverflow.com/questions/29625182/gulp-browserify-takes-longer-to-compile-on-each-save-change/29660913#29660913

**Comment by ngryman** [comment]
btw, right code:

```javscript
var bundler = watchify(
  browserify('./src/index.js', watchify.args).transform(babelify)
)
```

wrong code:

var bundler = watchify(
  browserify('./src/index.js', watchify.args)
).transform(babelify)
```

**Comment by jmm** [comment]
@ngryman both of the ways you illustrated should be fine. The point I was making in the SO answer is to not call `.transform()` in the `update` handler. Do you actually get a performance difference between the 2 versions you illustrated?

**Comment by zertosh** [comment]
@ngryman, like @jmm said, those two versions are essentially equivalent – do you actually see a diff between them?

**Comment by ngryman** [comment]
Oh man, you are totally right, I think I've been too quick on this one. Sorry about that guys!

That said, it would be nice if you mention that `transform` should be at the bundler declaration level only. 
I know it's not directly related to `babelify` but I have the feeling I'm not the only *in-a-rush* guy that will make this dumb mistake, and performance impact is quite terrible...

Thanks!

**Comment by jmm** [comment]
@ngryman NBD :smiley: If anything I'd say add a note to the watchify docs, and at most link to it from individual transforms. It's really a watchify / platform issue that shouldn't be explained in duplicate in every browserify transform.

**Comment by ngryman** [comment]
@jmm Alright.
