### ISSUE TITLE
Compiling code that uses library installed via npm link failes

### ISSUE THREAD

**Issue by polkovnikov-ph** [babel/babelify#117]
When doing a `babelify` transform after some previous transform on the sources that include some library via `npm link`, and if that library contains something like `Object.keys`, `babelify` makes build fail due to missing `babel-runtime` properties.

     watchify ... -t reactify -t [ babelify  --optional "runtime" ] ...

     Error: Cannot find module 'babel-runtime/core-js/object/keys' from '...\thrift\lib\nodejs\lib\thrift'

While if the library is reinstalled via `npm install` and it still contains `Object.keys`, it works OK.

The part of the message `from ...` doesn't point to an exact file, but to the whole library folder, and that doesn't seem like a correct behaviour also, because it takes time to look through all the sources of the library to find that `Object.keys`.

Also I don't understand why `babelify` even starts transforming that library, because default `browserify` behaviour for `-t` is to transform all the sources except libraries.

**Comment by jmm** [comment]
I think these are browserify issues that just happen to be visible via babelify. See:
https://github.com/substack/node-browserify/issues/1386
https://github.com/substack/node-browserify/pull/1365

> The part of the message `from ...` doesn't point to an exact file, but to the whole library folder, and that doesn't seem like a correct behaviour also

Couldn't agree more. I've been trying to fix that:
https://github.com/substack/node-resolve/issues/60
https://github.com/substack/node-resolve/pull/64

**Comment by polkovnikov-ph** [comment]
Okay, there seems to be a workaround. `babelify` has `--ignore <regex>` flag. To get rid of these errors I have to put just two folders there. Single folder name works well there, but passing `a|b` regex is impossible, because `|` is special char in command line. If I put it like `"a|b"`, neither directory gets ignored. What am I doing wrong?

**Comment by jmm** [comment]
@polkovnikov-ph What's your browserify version?

**Comment by polkovnikov-ph** [comment]
@jmm
watchify v3.2.3
browserify v10.2.6

**Comment by jmm** [comment]
@polkovnikov-ph Thanks. Not sure about your `ignore` pattern -- could you try `'{a,b}'` and see what happens?

**Comment by zertosh** [comment]
@polkovnikov-ph are you still having this problem?

**Comment by velomash** [comment]
I was experiencing this bug with babelify + browserify: "3.0.0". I upgraded browserify to "^4.0.1" and it was solved. You can probably close this.
