### ISSUE TITLE
Error: Cannot find module 'foo'

### ISSUE THREAD

**Issue by synthecypher** [babel/babelify#118]
```javascript
// ~/babel-project/bar.js
import foo from "foo";
console.log(foo);
```

```javascript
// ~/babel-project/foo.js
export {test};
export var test = 5;
```

```bash
$ cd ~/babel-project
$ browserify foo.js -t babelify -o bundle.js
Error: Cannot find module 'foo' from '~/babel-project
```

What am I doing wrong?

```
node v3.0.0
├── babel@5.8.23
├── babelify@6.3.0
├── bower@1.4.1
├── browserify@11.2.0
├── gulp@3.9.0
└── npm@2.13.3
```

**Comment by jmm** [comment]
@synthecypher 

You don't need to do both of these:
```js
export {test};
export var test = 5;
```

I forget if it's an error to do it.

You can do either:
```js
export var test = 5;
// Or
export {test}
var test = 5;
```

In this case you probably need:

```js
import foo from "./foo";
```

Also, what role does `bar.js` play in this? You don't mean?:

```sh
$ browserify bar.js -t babelify -o bundle.js
```

**Comment by synthecypher** [comment]
I made a few typos in my example I meant to target `bar.js` instead of `foo.js`.

Importing `./foo` instead of `foo` worked, I forgot that was needed.

```javascript
// foo.js
var foo = 5;
export {foo};
```


```javascript
// bar.js
import foo from "./foo";
console.log(foo);
```

It now compiles `bundle.js` but when I run `bundle.js` via `node` I get the output of `undefined` instead of the expected output of `5`?

Any ideas?

**Comment by anthonylebrun** [comment]
@synthecypher I was about to tear all of my hair out before I read your solution :)
