### ISSUE TITLE
Errors contain ANSI Escape Codes

### ISSUE THREAD

**Issue by InfinitiesLoop** [babel/babelify#119]
If I run babel directly in bash on a file with a syntax error, it outputs a nice colored error message that points to the syntax error.

When I do the same thing via gulp/browserify/babelify, the output contains raw ANSI escape codes. It's as if whatever is retrieving the output of babel is escaping it, causing the embedded escape codes to be, well, escaped. This makes the error message really difficult to understand, slowing down development.

My gulp task looks like this:

    var b = browserify({
        entries: PATHS.mainjs,
        debug: true,
        noParse: ["jquery"]
    });
    b.on('log', gutil.log);

    b = b.transform(babelify);

    return b.bundle()
        .pipe(source(PATHS.bundlejs))
        .on('error', gutil.log)
        .pipe(gulp.dest(PATHS.dist + '/js'));

The error looks like this:

    SyntaxError: d:/git/exceptionsweb/src/js/pages/app.js: Unexpected token (43:14)
    ?[0m  41 |                                              ?[36mthis?[39m?[1m.?[22mstate?[1m.?[22mprojectsLoading
      42 |                                                  ?[1m??[22m ?[1m<?[22mdiv?[1m>?[22mLoading?[1m...?[22m?[1m<?[22m?[1m/?[22mdiv?[1m>?[22m

The "?" are actually the escape character, but that doesn't translate well here. 

I'm also not really sure how this error is being output. It's not coming from my on("error") callback, because I get it even if I comment that out. Same with on("log"). It's like babel is writing directly to the output.

babelify 6.3.0
babel-core 5.8.25
gulp 3.9.0

Any help would be appreciated!

**Comment by zertosh** [comment]
That's an issue with `gutil.log` - if you use `console.log.bind(console)` directly, it should output ANSI escapes correctly.

**Comment by InfinitiesLoop** [comment]
I've tried that. Like I mentioned, I don't see how that makes a difference, since I get the error even if I don't have a on("error") or on("log") callback registered at all. Commenting them out has no effect. Changing them to console.log has no effect.

**Comment by zertosh** [comment]
Ah, the error handler is on the wrong stream - so the output you're seeing is from node exiting. Try:

```js
return b.bundle()
    .on('error', gutil.log)
    .pipe(source(PATHS.bundlejs))
    .pipe(gulp.dest(PATHS.dist + '/js'));
```

**Comment by InfinitiesLoop** [comment]
Well, that gives me a different error, but it still has escaped tab characters and ANSI codes :(

    { [SyntaxError: d:/git/exceptionsweb/src/js/pages/app.js: Unexpected token (41:14) while parsing file: d:\git\exceptionsweb\src\js\pages\app.js]
      pos: 1003,
      loc: Position { line: 41, column: 14 },
      _babel: true,
      codeFrame: '\u001b[0m  39 | \t\t\t\t\t\t\u001b[36mthis\u001b[39m\u001b[1m.\u001b[22mstate\u001b[1m.\u001b[22mprojectsLoading\n  40 | \t\t\t\t\t\t\t\u001b[1m?\u001b[22m \u001b[1m<\u001b[22mdiv\u001b[1m>\u001b[22mLoading\u001b[1m...\u001b[22m\u001b[1m<\u001b[22m\u001b[1m/\u001b[22mdiv\u001b[1m>\u001b[22m\n> 41 | \t\t\t\t\t\t\t\u001b[1m:\u001b[22m \u001b[32m{\u001b[39m\u001b[36mthis\u001b[39m\u001b[1m.\u001b[22mprops\u001b[1m.\u001b[22mchildren\n     |               ^\n  42 |
    \t\t\t\t\t\u001b[32m}\u001b[39m\n  43 | \t\t\t\t\t\u001b[1m<\u001b[22m\u001b[1m/\u001b[22mdiv\u001b[1m>\u001b[22m\n  44

**Comment by zertosh** [comment]
That's the error object. If you want just the _colored message_, you need to `console.log(err.codeFrame)`. And if you want the exact error formatting that babel-cli uses, then you can find it [here](https://github.com/babel/babel/blob/e2d673dafa8b88604e2738916e0235ffc0852de8/packages/babel-cli/src/babel/util.js#L58-L64).

**Comment by InfinitiesLoop** [comment]
Thanks. I settled on this after some searching:

        .on("error", function(err) {
            gutil.log(err.message + "\r\n" + err.codeFrame);
            this.emit("end");
        })

That seems to give a nice output, but I'm unsure whether all the types of errors it might get would map well to this. Thanks for your help!

**Comment by zertosh** [comment]
Sure np. The babel-cli (see the link above) only shows that error for `if (err._babel && err instanceof SyntaxError) {`, otherwise it logs the error's stack - you can do that too.

**Comment by InfinitiesLoop** [comment]
Here we go, getting fancy now.

        .on("error", function(err) {
            if (err && err.codeFrame) {
                gutil.log(
                    gutil.colors.red("Browserify error: "),
                    gutil.colors.cyan(err.filename) + ` [${err.loc.line},${err.loc.column}]`,
                    "\r\n" + err.message + "\r\n" + err.codeFrame);
            }
            else {
                gutil.log(err);
            }
            this.emit("end");
        })

**Comment by zertosh** [comment]
Cool. Glad you got it working the way you wanted.

**Comment by gusaiani** [comment]
@InfinitiesLoop Thank you for that. :+1:
