### ISSUE TITLE
Babel 5.8.25 for React optimisations

### ISSUE THREAD

**Issue by leebenson** [babel/babelify#122]
Can this package.json be upgraded to babel-core 5.8.25?

5.8.24 introduced React optimisations.

**Comment by jmm** [comment]
@leebenson You just need to update your `babel-core` dep or reinstall `babelify`.

**Comment by leebenson** [comment]
sorry my bad, I read the npm version as a ~ instead of a ^ - I see that it'll update automatically by reinstalling. Thanks @jmm
