### ISSUE TITLE
any way to expose `metadata`?

### ISSUE THREAD

**Issue by erwinmombay** [babel/babelify#123]
i'd like to get to metadata.usedHelpers to construct my custom `babel-helpers` file after passing it through browserify/babelify, is there any way for me to do this?

**Comment by zertosh** [comment]
hmmm I guess it can emit an event that you can subscribe to and get it there. Does that work for you?

**Comment by erwinmombay** [comment]
@zertosh that would be perfectly fine :)

**Comment by mbrevda** [comment]
Hey - this event is awesome, totally saved the day!

When using browserify with watchify, could it be this even is only emitted once? Ideally, I would like it to run every time the code updated...
