### ISSUE TITLE
Object has no method 'canCompile'

### ISSUE THREAD

**Issue by JacksonGariety** [babel/babelify#125]
This seems like there should be an obvious answer but I've spent some time with it and can't figure it out.

I run: `browserify foo.js -t babelify`

No matter what foo.js contain, even no code at all, I get: `TypeError: Object #<Object> has no method 'canCompile'`

It's from `index.js:56`:
    if (!babel.canCompile(filename, extensions)) {

That method simply does not exist.

**Comment by yuezk** [comment]
Same issue here.

I installed this package just now with Node.js 4.2.1

**Comment by JacksonGariety** [comment]
I was so surprised I thought, "no way the package has been updated in the last 30 minutes, I must've fucked something up."

Nope, it just got pushed.

**Comment by yuezk** [comment]
I find that `babel-core` updated it's code in the past 8 hours, and removed the `canCompile` export. Go to https://github.com/babel/babel/commit/ae7d5367f1c3d438667242d6925db024f875fccd and search `babel-core/src/api/node.js`, you will find that `export { canCompile } from "../util"` was deleted.

**Comment by tanem** [comment]
Saw this too. Using `6.4.0` in the meantime while I figure out some other issues with my app :sweat_smile: 

Re @yuezk comment above, [here's the direct link](https://github.com/babel/babel/commit/ae7d5367f1c3d438667242d6925db024f875fccd#diff-4f7a3a65a4c37780e71d32cd3adabe0cL11).

**Comment by yuezk** [comment]
The `babel-core` has updated to `6.x`, it was not compatible with `5.x`, and the `babelify` should not update it's dependency, all the test case were failed, not just `canCompile` error.

**Comment by MayhemYDG** [comment]
@sebmck ^

Also the release commit seems to be missing?

**Comment by sinkingshriek** [comment]
This timing is uncanny. I start my first hello world react program and I was constantly getting this. Since I was a noob at this I thought I must have done something wrong. Scratched my head for good 2 hours (took a nap in between too :smile:  ) However, I did see [this](https://twitter.com/babeljs/status/659791588239912960) earlier today though. I should have made the connection.

**Comment by sebmck** [comment]
@MayhemYDG 

> Also the release commit seems to be missing?

Erm, no it's [not](https://github.com/babel/babelify/commit/ca33378c9773ee973952991c2ece22c01ce23cf8)?

**Comment by sebmck** [comment]
Fixed as of 7.0.1.

**Comment by MayhemYDG** [comment]
![image](https://cloud.githubusercontent.com/assets/567105/10838193/f6b3e1aa-7ec2-11e5-8a9b-31d394045d3b.png)
:^)

**Comment by JacksonGariety** [comment]
@sebmck wow thanks for the quick fix!

Not sure how this can be prevented in the future, the timing is jsut really bad. Perhaps it's just a matter of using the `~` symbol in `package.json`? That way breaking change to babel won't break babelify when you make two changes like this.

**Comment by JacksonGariety** [comment]
@sebmck after 7.0.1 I now get:

    ReferenceError: [BABEL] /Users/Jackson/Sites/4charts/src/client.js: Unknown option: base._

Seems like something to do with .babelrc so I removed it but same error. Any ideas? It worked a couple hours ago, so I think it's on babel's end. Could b wrong.

**Comment by sinkingshriek** [comment]
@JacksonGariety, so that happened to me too. I fixed that by including two more plugins (don't know if you need the react one if you're not using react) in `.babelrc`. I'm still trying to figure out without using `.babelrc`.

```js
{
	"presets": ["react", "es2015"],
	"plugins": [
      "transform-es2015-modules-commonjs",
      "transform-react-constant-elements",
   ]
}
``
