### ISSUE TITLE
v7.1.0 throws syntax errors for JSX

### ISSUE THREAD

**Issue by azer** [babel/babelify#131]
Babelify fails to compile React & ES6 files with syntax errors. v6.1.3 works fine.

**Comment by zertosh** [comment]
As of v7.0.0, babelify uses babel 6.0.0, which fundamentally changed the API. babel – and thus babelify – now explicitly require you state the transforms you'd like to run via "presets" or "plugins". See https://babeljs.io/blog/2015/10/29/6.0.0/ and https://github.com/babel/babelify#options.

**Comment by azer** [comment]
How do we choose it if we're using just command-line browserify & watchify ?

**Comment by zertosh** [comment]
![cli-use](https://cloud.githubusercontent.com/assets/830952/10866960/8c19f02e-8006-11e5-99c6-9f5987fab187.png)

**Comment by yaycmyk** [comment]
I'm having issues with this too and I think it is `babelify` related. I installed the babel-cli to test a specific file directly without the browserify build chain and it worked properly, but running the same file through babelify with the same settings gave me an unexpected token error when it reached a JSX fragment.

I've tried including my preset in various ways: the `babel.presets` package.json field, the `browserify.transform["babelify"]` field and in a `.babelrc`... none of them seem to pay any attention to the passed preset.

But if I execute `babel file.js --preset react` it works perfectly. What gives?

**Comment by yaycmyk** [comment]
An update...

It only works if I specify the transform in the command (does not inherit from package.json or elsewhere).

It would be ideal if `babelify` could read from the normal places babel allows for configuration like `.babelrc` and the `babel` package.json field. I also tried passing the config into the browserify package.json transform field and `babelify` ignored the information:

```json
{
  "browserify": {
    "transform": [
      ["babelify", {"presets": ["es2015", "react"]}]
    ]
  }
}
```

**Comment by zertosh** [comment]
@yaycmyk Can you provide me with a repo where I can reproduce the issue?

**Comment by yaycmyk** [comment]
@zertosh see my follow up comment there. Babelify seems to only allow you to configure the presets via command line vs in package.jaon or in the application's babelrc file

**Comment by yaycmyk** [comment]
My current project is private - I can throw together something though if necessary

**Comment by zertosh** [comment]
The case you're describing is already a unit test - so yeah a quick something would be really useful. https://github.com/babel/babelify/blob/master/test/browserify-package.js

**Comment by yaycmyk** [comment]
@zertosh Here you go: https://github.com/yaycmyk/xyz

**Comment by zertosh** [comment]
@yaycmyk Your problem **is** invalid syntax. `return { <div /> }` isn't valid JSX. Remove the curly braces.

**Comment by yaycmyk** [comment]
@zertosh My bad - a hastily thrown together example. I adjusted it and the minimal case does compile successfully now. I'm going to dig further into my stack then, there must be malformed syntax somewhere.

Thanks for your help.
