### ISSUE TITLE
Source maps are always generated inline

### ISSUE THREAD

**Issue by arieh** [babel/babelify#132]
I have this configuration on my grunt file:
```
transform: [babelify.configure({
                    sourceMap : false,

                    presets: ["es2015"],
                    sourceType : 'module'
                }), 'brfs', 'browserify-shim' ]
```

But my files always have inline source maps in them.
I checked and the babel documentation and they say the parameter should be `sourceMaps`, not `sourceMap` however the babelify code actually only uses the later.

I have tried pretty much any configuration but they will always be generated inline. 

Any idea how I can prevent this behavior?

(I would really like to have them generated externally, but in any case never inline since they are huge)

Thanks!

**Comment by zertosh** [comment]
`sourceMap` is an [alias](https://github.com/babel/babel/blob/9702ceb07476d9bf0da5eed8e236af8bd45ae8b3/packages/babel-core/src/transformation/file/options/config.json#L104-L114) to `sourceMaps`. And it's working correctly for me. If you're seeing an inline source map in your output bundle, you probably have the browserify `debug` option set to `true`.

**Comment by arieh** [comment]
yep - debug:true was set on browserify.
