### ISSUE TITLE
Error: Couldn't find preset

### ISSUE THREAD

**Issue by bioball** [babel/babelify#134]
Am on babelify version 7.1, and browserify version 12.0.1.

I'm using the CLI to create a build file, and am getting an error. As far as I can tell, I'm doing everything the vanilla, correct way. If I take out presets option, I get unexepcted token errors.

Here's the command I'm running:

```
browserify -e src/index.js -t [ babelify --presets es2015 ] -o dist/mandolin.js -s mandolin
```

And here's the error and stack:

```
Error: Couldn't find preset while parsing file: <root_dir>/src/index.js
    at OptionManager.mergePresets (<root_dir>/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:309:17)
    at OptionManager.mergeOptions (<root_dir>/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:269:12)
    at OptionManager.init (<root_dir>/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:10)
    at File.initOptions (<root_dir>/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (<root_dir>/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (<root_dir>/node_modules/babelify/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Babelify._flush (<root_dir>/node_modules/babelify/index.js:28:24)
    at Babelify.<anonymous> (_stream_transform.js:130:12)
    at Babelify.g (events.js:180:16)
    at Babelify.EventEmitter.emit (events.js:117:20)
```

**Comment by andolf** [comment]
+1

**Comment by andolf** [comment]
Googled around a bit and this solved my issue: Install `babel-preset-es2015` via NPM and also `babel-preset-react` if you're also running React.

**Comment by bioball** [comment]
Oh, nice, that fixed it for me too. Maybe this should be added to the readme?

**Comment by zertosh** [comment]
Sure I guess, I'll take a PR for that. Keep in mind though, that the babelify docs are not a substitute for the babel docs. The es2015 preset page already tells you how to install it: http://babeljs.io/docs/plugins/preset-es2015

**Comment by CorpusCallosum** [comment]
Sure I guess, I'm getting the same issue even after I install the preset.
running: ```npm install --save-dev babel-preset-es2015```
then: ```browserify -t [ babelify --presets [ "es2015", "react" ] ] src/main.js -o public/js/bundle.js```

Getting the error: ```Error: Couldn't find preset "es2015,"```

**Comment by bioball** [comment]
@CorpusCallosum try running that without quotes around `es2015` and `react`.

**Comment by CorpusCallosum** [comment]
Hey Dan, I tried that, getting the same error.

On Fri, Jan 22, 2016 at 3:52 PM, Daniel Chao <notifications@github.com>
wrote:

> @CorpusCallosum <https://github.com/CorpusCallosum> try running that
> without quotes around es2015 and react.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babelify/issues/134#issuecomment-174042996>.
>



-- 
Jack Kalish
www.jackkalish.com

**Comment by whitelynx** [comment]
@CorpusCallosum It looks like you need to remove the comma after `"es2015"`, since you're running it on the command line. (in JS, the comma is part of the language; on the command line, it's just interpreted as part of a normal token)

**Comment by ORESoftware** [comment]
$  npm install --save-dev babel-preset-stage-3

was solution for me

**Comment by happy2share** [comment]
Adding `babel-plugin-transform-react-jsx-source` as dev dependency and modifying .babelrc file as below helped me
```
{
"presets": ["react-native-stage-0/decorator-support"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}
```

**Comment by zanona** [comment]
This is still an issue when using `--global-transform` rather than `--transform` it will try to search for the preset relative to the nested module being converted. This will happen when you `link` a module that's located elsewhere locally and not flattened under `/node_modules` 

Cross-reference: https://github.com/babel/babel-preset-env/issues/186

**Comment by HuangHongRui** [comment]
@ORESoftware  Thanks.. Dude
>> `$ npm install --save-dev babel-preset-stage-3`<<
Work For Me ~
