### ISSUE TITLE
Incorrect export when using ES6 export syntax

### ISSUE THREAD

**Issue by electerious** [babel/babelify#139]
Hi,

I'm currently making the switch to Babel 6 and running into the following problem, which might* be related to babelify.

Here's my gulp-task:

```js
let bify = browserify({
	entries    : './src/scripts/main.js',
	standalone : 'basicContext'
})

let transformer = babelify.configure({
	presets: ['es2015']
})

bify.transform(transformer)
    .bundle()
    .on('error', catchError)
    .pipe(source(name + '.min.js'))
    .pipe(buffer())
    .pipe(plugins.uglify())
    .on('error', catchError)
    .pipe(gulp.dest('./dist'))
```

`main.js` exports a function:

```js
export default function(e, items, opts = {}) { … }
```

As I'm bundling this file as a standalone UMD module, I expected the variable `basicContext` to be a function. This was the case before I updated babelify and babel. Now `basicContext` is the following:

```js
console.log(basicContext)
// {__esModule: true, default: function}
```

Best
Tobias

* Could be cased by Babel 6, too. It's really not easy to find the dependency casing the issue.

**Comment by zertosh** [comment]
That's the correct behavior because you're exporting a es6 module. It's babel that is doing that. I don't know why Babel 5.0 would've given you a different result.

**Comment by jmm** [comment]
If that's the only export, this sounds like https://github.com/babel/babel/issues/2212.

**Comment by zertosh** [comment]
Ah. I didn't know that was the old behavior. I don't use modules.

Rant: I don't understand why you'd use modules if your target platform doesn't support them. If you're transpiling them now to get around some circular dependency issue, then maybe that's valid. Other than that, you're just making things more complicated for marginally prettier syntax.

**Comment by electerious** [comment]
@zertosh This allows users to require basicContext as a module if they want OR they can use `window. basicContext` like in the good old days.

> Generate a UMD bundle for the supplied export name. This bundle works with other module systems and sets the name given as a window global if no module system is found. (https://github.com/substack/node-browserify#usage)

I will take a deeper look at babel/babel#2212 to find out if this is casing the problem. As far as I saw it look like something different. Exporting a function via `export default function() …` should be correct as far as I know.

**Comment by zertosh** [comment]
@electerious, I'm not talking about `standalone` - I'm talking about `export`. You can easily just do `module.exports = function() {}` from main, and your users will be able to require the module or access the global.

**Comment by jmm** [comment]
@zertosh There are rationales for and against. One thing I'd note is that people using it now is probably providing invaluable insight into interop issues that'll have to be resolved in the Loader spec.

**Comment by zertosh** [comment]
> One thing I'd note is that people using it now is probably providing invaluable insight into interop issues that'll have to be resolved in the Loader spec.

Agreed. But I've seen a lot use in the wild just for the syntax w/o an understanding of what ES6 modules are, and how they're different from a plain CommonJS `module.exports`.

**Comment by jmm** [comment]
Oh totally, it's not well understood yet by a lot of people. A lot of people don't even appreciate the difference between the syntax and the loading mechanism. I think a couple of the motivations are that people feel like it's a bit incongruous to write modules that use other ES2015 syntax, but not the module syntax, and that people like the idea of writing the module syntax now, having it work via compilation, and then just continue to work when it's supported natively. There are some interop questions and hazards around that though (as illustrated by this issue).

**Comment by zertosh** [comment]
:+1: – and sorry for hijacking your thread @electerious

**Comment by electerious** [comment]
@zertosh No problem.

@jmm Totally agree. Things will get clearer as soon as we can use the ES2015 module syntax natively. It's hard to understand what's really happening when the executed code isn't the code you write. Lots of stuff happens in the background when using browserify and babel.

Back to topic: There's a handful of babel issues regarding ES2015 module syntax and classes. I will keep an eye on them. As said: No matter if using the syntax now is a good idea or not. Exporting a function via `export default function() …` should be correct.

Will close the issue, but keep you updated.

**Comment by jmm** [comment]
@electerious It's not really the export that's the problem. That is the best you can do with ES2015 module syntax. It's a design change in what Babel compiles it to and what that means for CommonJS interop. You have a few options (at least):

* Just write ES5 CJS (like @zertosh suggested): `module.exports = function () {}`.
* Split your module in 2: keep your ES2015 module and make a new `main.js` that does `module.exports = require("real-main").default;`.
* Make your `main.js` a stream that does that, if you want to avoid creating a new physical file (e.g. `stream.end('module.exports = require("main").default'); browserify(stream);`
* Create a transform that adds something like this to `main.js`: `module.exports = exports.default; Object.keys(exports.default).forEach(function (key) { return if (key !== "default") module.exports[key] = exports[key]; });`

**Comment by electerious** [comment]
@jmm You're right. Thanks a lot for attaching some options.

> Create a transform that adds something like this to main.js: module.exports = exports.default; Object.keys(exports.default).forEach(function (key) { return if (key !== "default") module.exports[key] = exports[key]; });

For those who are interested: [undefaultify](https://www.npmjs.com/package/undefaultify) does something similar.

**Comment by electerious** [comment]
I now understand why it still works in other projects. Here's a quick example:

Exporting the following and packaging it as a standalone UMD module using browserify …

```js
export const a = function() { … }
export const b = function() { … }
```

… will produce the following output:

```js
{__esModule: true, a: function, b: function, …}
```

As I'm always calling the functions using `moduleName.a` and `moduleName.b`, everything works fine. However, when using `export default` the produced object will contain a `default` property. Calling the function using `moduleName()` won't work. I need to use `moduleName.default()` instead.

The reason for this—and correct me if I'm wrong—is the fact that you can use both `export` and `export default` inside a single module. That's not possible in CommonJS. The added `default` property is a workaround to make both "compatible".

**Comment by jmm** [comment]
@electerious That's pretty much it.

The big difference is that CJS modules export an object while ES2015 modules export bindings, one of which, `default`, gets some special treatment via syntactic sugar. The way to do a default export in CJS is by assigning to `module.exports`. But then to also have named exports they have to be properties of the object assigned to `module.exports`. That's not the case with ES2015, where modules only export named bindings.

`default` is just a named binding that has some special syntax associated with it for convenience. Using the ES2015 default export mechanism doesn't require polluting the `default` export with the other exports.

So a way to approximate ES2015 modules in CJS is to assign the `default` export to `exports.default`, which then requires it to be imported via `require("x").default` in CJS. Another opinion on approximating that would be to assign the the `default` export to `module.exports`, which is what Babel v5 did. You can see the issue I linked earlier for the rationale for changing it.

**Comment by runemadsen** [comment]
First of all, thanks for all the hard work on this lib. I'm really loving writing my lib in ES2015, and compiling both for node and for the browser with Browserify. So huge thumbs up!

As I can't comment on the other locked ticket, I'll just go put my two cents here. I feel that this `export default` change was a bad decision. I understand the rationale for doing it, but the result is that developers are not able to transform their ES2015 modules into node modules, in the way that 99% of other node modules work. It is now impossible to ship a module function that can be required by using the module name.

What about giving users the ability to toggle this on? It's frustrating having built a library, released it into the wild, taught CS students how to use it, and then being told that I can't do in a newer version what I did in an earlier version.

**Comment by jmm** [comment]
@runemadsen **sebmck** has said he has no intention of having it in Babel core even as an option. I consider that a settled issue. I've thought about making a module formatter plugin that does it in some fashion.

**Comment by runemadsen** [comment]
Thanks for the quick reply. I found [this](https://www.npmjs.com/package/undefaultify), but I'm not sure I'm a huge fan of the regexp approach.

**Comment by runemadsen** [comment]
Also, for those of you interested, this is my terrible hack to change thi behavior in my gulp pipeline:

```
.pipe(replace("exports.default = MyFunction;", "module.exports = MyFunction;"))
```

**Comment by reintroducing** [comment]
I just ran into this when upgrading to 7.2.  From my understanding, after this update, the correct way to import ES6 modules is something like this:

```
import {default as Foo} from 'foo';
```

where Foo is the following: 
```
class Foo extends React.Component {
    ...
}

export default Foo;
```

Am I way off base here or is this the preference moving forward?  I'd appreciate any help on this.

**Comment by reintroducing** [comment]
I just wanted to follow up and say this only seems to be an issue when using Babel and requiring ES6 modules inside of ES5 modules.  Just now made that realization, sorry for the noise :\
