### ISSUE TITLE
The 'presets' cli flag doesn't do anything

### ISSUE THREAD

**Issue by lorenmh** [babel/babelify#140]
This may very well be an error on my part, but this was my experience with using the 'preset' flag for babelify's command line interface:  

I installed babel-preset-es2015 as per your instructions.  Then I attempted to transform a simple test file with the contents of:
```
() => 'works';
[ a, b, ...foo ] = [ 1, 2, 3, 4, 5 ];
```

**None of this code was transformed to es5 until I used a .babelrc file in the project root**  

The only way I could get it to work was to add the es2015 and react presets to a .babelrc file (this is not in your instructions).  I then removed the presets flag entirely from the command I was using and babelify still transforms es6 to es5.  In other words, with a .babelrc file both of these commands have the same output:  

```
browserify -t babelify --presets es2015 -e foo.js -o bar.js
```

```
browserify -t babelify -e foo.js -o bar.js
```

Ie, the presets flag doesn't do anything.  The only way I could get this to work was by creating a .babelrc file with the presets in it.  The instructions make it seem otherwise.

**Comment by jmm** [comment]
You're overlooking the subarg syntax and just passing options to browserify:

```
-t [ babelify --presets [ es2015 react ] ]
```

**Comment by lorenmh** [comment]
thanks @jmm , user error on my part, closing

**Comment by qckanemoto** [comment]
+1
