### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by slackeast** [babel/babelify#141]
This line of code in babelify 6.4.0 works:

<code>import {User} from '../lib/User';</code>

However, in 7.2.0 I know get the following error:

<code>Error: Parsing file /home/prisoner/jdeveloper/List/FF/webroot/js/app.js: 'import' and 'export' may appear only with 'sourceType: module' (3:0)</code>

Is this a bug or am I doing something wrong?

Thanks for you help

**Comment by slackeast** [comment]
I'd thought I would add my User.js lib code below:

<code>export class User {

    constructor(eb) {
        this.eb = eb;
    }
    
    register( json ) {
        this.eb.send('fflist-register', json);
    }
    
    
    logIn() {
        
    }
    
    getName() {
        
    }
}

**Comment by zertosh** [comment]
You upgraded to babelify 7.0, which uses the new babel 6.0, and you're missing options. Please checkout the README.
