### ISSUE TITLE
Nested array in package.json transform field?

### ISSUE THREAD

**Issue by mikemaccana** [babel/babelify#142]
Thanks for the great project! I'm having trouble with some syntax from the docs that doesn't seem to be covered in browserify's own documentation - I'm not sure if this is a babelify issue or just browserify's documentation missing something.

https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed mentions:

    {
      "browserify": {
        "transform": [["babelify", { "presets": ["es2015"] }]]
      }
    }

I know 'transform' is an array of transforms, but what is the nested array inside it? The [browserify docs don't mention this syntax](https://github.com/substack/browserify-handbook#browserifytransform-field). Is it correct that using, say, brfs and babelify would look like this?

	"browserify": {
		"transform": [
			"brfs",
			[
				"babelify", { 
					"presets": ["es2015"] 
				}
			]
		]
	}

Or should another data structure (eg an Object) be used?

**Comment by mikemaccana** [comment]
Hrm it seems other packages also use the undocumented / array-not-used-as-array syntax, so I suspect this is a bug in the browserify:

https://github.com/css-modules/browserify-demo/blob/master/package.json

**Comment by zertosh** [comment]
The [`browserify.transform` docs](https://github.com/substack/node-browserify#browserifytransform) link you to module-deps where that syntax is [mentioned](https://github.com/substack/module-deps#packagejson-transformkey)

**Comment by mikemaccana** [comment]
Thanks @zertosh. I've filed a separate bug (above) to make the syntax less bizarre.

**Comment by zertosh** [comment]
@mikemaccana The reason the syntax is bizarre is because it has to be CLI friendly. Since this is the form that comes from [subarg](https://github.com/substack/subarg), that's the format that's used everywhere else. Otherwise you'd have to parse options in two different ways.

**Comment by mikemaccana** [comment]
Cheers. I understand there's a command line different. Parse options two different ways sounds best: you'd get logical JS and still be able to function on the command line.
