### ISSUE TITLE
Converting node module from es6 to es5 

### ISSUE THREAD

**Issue by dineshi2it** [babel/babelify#143]
I'm using react with sails. I have a node module joi which is written in es6, needs to be converted to es5. Following is the workaround I made. Please help me out.

my package.json

  "browserify": {
    "transform": [
      "babelify"
    ]
  }

.babelrc

{
    "presets": ["react", "es2015"],
    "plugins": [
      "transform-es2015-modules-commonjs",
      "transform-react-constant-elements",
   ]
}

error:

/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, Refe
                            ^
TypeError: Cannot call method 'error' of undefined

**Comment by zertosh** [comment]
Can you provide me with a repo that I can use to reproduce the issue?

**Comment by dineshi2it** [comment]
I think it would take more time to create a repo. Can you please guide me on converting a js file from ES6 to ES5. I think I have misconfigured something.

**Comment by zertosh** [comment]
On the surface what you're doing looks fine. I can't help you beyond that unless I have a way to reproduce the issue. Sorry.

**Comment by dineshi2it** [comment]
Thanks it works now!!

**Comment by dana-shalev** [comment]
Hi,
I have the same problem. Can you please tell me how was the issue resolved on your env?
Thanks!

**Comment by dineshi2it** [comment]
I have tried lot of options to babelify the code and so finally I ended up by removing node modules and installed it again. It worked.

**Comment by knappg** [comment]
I'm seeing this as well. I've tried removing node_modules and re-installing to no avail. Do you mind telling us what version of the preset your using, or the relevant depencies in your package.json? It sounds like it would definitely help others.

**Comment by sawangupta** [comment]
I have run into the same issue. Re-installing hasn't helped. Any specific version that is causing this ? My package.json has:

"dependencies": {
    "axios": "^0.7.0",
    "express": "^4.13.3",
    "history": "^1.9.1",
    "immutable": "^3.7.5",
    "object-assign": "^4.0.1",
    "react": "^0.14.0",
    "react-dom": "^0.14.0",
    "react-redux": "^4.0.0",
    "react-router": "1.0.0-rc3",
    "redux": "^3.0.0"
  },
  "devDependencies": {
    "babel": "^5.8.23",
    "babel-eslint": "^4.1.2",
    "babel-loader": "^5.3.2",
    "eslint": "^1.4.3",
    "eslint-plugin-react": "^3.3.2",
    "react-hot-loader": "^1.3.0",
    "webpack": "^1.12.1",
    "webpack-dev-server": "^1.11.0"
  }

**Comment by mancioshell** [comment]
@dineshi2it could you please post your solution? Maybe could help me and other people!
Thanks

**Comment by atombender** [comment]
@mancioshell @sawangupta This was a bug in babel-core around 5.8.24 or so. `log` is not assigned when the `OptionManager` is created. babel-core has been rewritten in 6.x, so you should use that.
