### ISSUE TITLE
【after update 7.0+】 shows 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by tommyZZM** [babel/babelify#144]
how to slove this?

backward to 6.4.0 everything is ok

````javascript
return browserify()
 .add(src)
 .transform(babelify)
 .transform(coffeeify)
 .transform(jadeify)
 .bundle()
 .pipe(source(out))
 .pipe(buffer())
````

**Comment by zertosh** [comment]
You upgraded to babelify 7.0, which uses the new babel 6.0, and you're missing options. Please checkout the README.

**Comment by tommyZZM** [comment]
after adding
````
browserify().transform("babelify", {presets: ["es2015"]});
````
it shows 
Error: Couldn't find preset "es2015" while parsing file: e\proj\src\Main.js

**Comment by zertosh** [comment]
Please read the README.

> NOTE: Presets and plugins need to be installed as separate modules. For the above examples to work, you'd need to also install babel-preset-es2015 and babel-preset-react:

**Comment by tommyZZM** [comment]
fixed~ thx~
