### ISSUE TITLE
presets issue with projects mixing v6 and v5 version of babel

### ISSUE THREAD

**Issue by t0k4rt** [babel/babelify#145]
Using npm v 3.3.9
I use browserify + watchify + babelify to compile my react project.
Browserify is configured this way:
```
"browserify": {
    "transform": ["babelify"]
}
```
I've got one node module set up with a .babelrc file:
```
{"presets":["es2015"]}
```
I've got my main project compiled with babelify and babel-core v5
when the project is compiles I've got an option error: 
```
ReferenceError: [BABEL] 
.../node_modules/flux-datastore/lib/.....js: 
Unknown option: 
/.../node_modules/.../.babelrc.presets 
while parsing file: /.../node_modules/flux-datastore/....js
```
babel core v5 tries to compile with subproject options presets wich might not exists in that version.

I'm not sur if this is a babel or babelify issue. Any idea if this can be fixed in conf ?

**Comment by zertosh** [comment]
Try this https://github.com/babel/babel/issues/1503

**Comment by jmm** [comment]
FWIW that's not documented and [**sebmck** has explicitly said not to use it](https://github.com/babel/babel/issues/1633#issuecomment-105913977).

**Comment by t0k4rt** [comment]
Thanks a lot I'll try this :-)

Envoyé de mon Nokia 3110

**Comment by zertosh** [comment]
@jmm TIL

**Comment by krainboltgreene** [comment]
I'm having a similar issue I believe:

``` javascript
// ...
  return Browserify({ entries: SCRIPTS })
    .transform(Babelify, { presets: [ "stage-2" ] })
    .bundle()
// ...
``

``` cli
ReferenceError: [BABEL] 
source/file.js: Unknown option: direct.presets while parsing file: 
```

**Comment by zertosh** [comment]
@krainboltgreene What you're doing seems fine. It's one of the tests https://github.com/babel/babelify/blob/v7.2.0/test/aaa.js#L12 (it works with and without the array notation). Can you provide a small repro case?

**Comment by cameronjroe** [comment]
+1

**Comment by krainboltgreene** [comment]
Turns out I was using an old version of babelify, which in turn was using a pre-6 version of babel.

**Comment by kmudrick** [comment]
I am seeing this issue too - using babelify 7.2.0 with presets - when other (external) modules are required that were built with older versions of babel, babelify craps out.  

I can make it go away by removing the babel configuration from .babelrc and from package.json, but then  various other build tasks that rely on those being present break.

**Comment by zertosh** [comment]
@kmudrick multiple babelrc's and multiple versions are going to be a pain, but if you open a new issue with a small repro case, I'd be more than happy to take a look.

**Comment by danieldram** [comment]
This issue was also resolved for me by:
```sh
npm install babelify@7.2.x 
```

**Comment by mikemaccana** [comment]
Yep updating to `babel@6.3.26` and `babelify@7.2.0` resolved this for me.

**Comment by lmx99** [comment]
edit your package.json like below  and npm install agian, it will update to new version
`
    "babelify": ""
`

**Comment by adrianescat** [comment]
I have in my `gulpfile.js`

```javascript
require('babel-core/register');

var $ = require('gulp-load-plugins')();
var gulp = require('gulp');
var mkdirp = require('mkdirp');
var source = require('vinyl-source-stream');
var babelify = require('babelify');
var browserify = require('browserify');
var swift = require('ui-swift');

mkdirp('./build');

gulp.task('scripts', function () {
    return browserify({'entries': './src/scripts/boot.js', 'debug': false})
        .transform(babelify)
        .bundle()
        .pipe(source('app.js'))
        .pipe(gulp.dest('./build'));
});
```
*./src/scripts/boot.js was written in ES6 syntax*


my package.json

```json
{
  "name": "test",
  "version": "1.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "",
  "license": "MIT",
  "bugs": {
  },
  "devDependencies": {
    "autoprefixer-core": "5.2.1",
    "babel": "6.3.26",
    "babelify": "6.2.0",
    "browserify": "11.0.1",
    "gulp": "3.9.0",
    "gulp-base64": "0.1.3",
    "gulp-gzip": "1.2.0",
    "gulp-header": "1.7.1",
    "gulp-load-plugins": "0.10.0",
    "gulp-minify-css": "1.2.1",
    "gulp-postcss": "6.0.0",
    "gulp-rename": "1.2.2",
    "gulp-sass": "2.0.4",
    "gulp-uglify": "1.4.1",
    "gulp-util": "3.0.6",
    "mkdirp": "0.5.1",
    "vinyl-source-stream": "1.1.0"
  }
}
```
I installed this package too `babel-preset-es2015`

and a `.babelrc` with
```json
{
    "presets": [
        "es2015"
    ]
}
```

When I run `gulp scripts`  seems to work well reading the console logs but there isn't any output in the *build* directory, I was expecting to see a *transpiled app.js file*.
