### ISSUE TITLE
On ^7.2.0 getting: build failed: ReferenceError: [BABEL] Unknown option: base.stage

### ISSUE THREAD

**Issue by FullMontag** [babel/babelify#148]
When trying to run, I'm still getting:

ERROR in ./app/main.jsx
Module build failed: ReferenceError: [BABEL] /Users/nirmontag/Dev/Fanatico/node_modules/eslint-loader/index.js!/Users/nirmontag/Dev/Fanatico/app/main.jsx: Unknown option: base.stage

**Comment by zertosh** [comment]
You upgraded to babelify 7.0, which uses the new babel 6.0, and you're missing options. Please read the README.
