### ISSUE TITLE
ReferenceError: [BABEL]

### ISSUE THREAD

**Issue by cameronjroe** [babel/babelify#150]
Running babelify this morning.. Getting `ReferenceError: [BABEL]`. Head goes through monitor.. :/

`"babelify": "^7.2.0"`
`"babel-core": "^6.1.2"`
`"grunt-browserify": "^4.0.1"`
`"babel-preset-es2015": "^6.1.2"`

Included .babelrc and tried direct presets option. Any ideas?

**Comment by zertosh** [comment]
That's not enough information. Can you provide a repro case?

**Comment by cameronjroe** [comment]
```
Unknown option: /path/.babelrc.preset while parsing file: /path/js/_index.js
```

**Comment by zertosh** [comment]
try `presets` – plural

**Comment by cameronjroe** [comment]
Okay, missed that. Thanks.

**Comment by bORm** [comment]
what try?
i run gulp by console
