### ISSUE TITLE
babel-plugin-transform-flow-strip-types includes imported flow types

### ISSUE THREAD

**Issue by mhagmajer** [babel/babelify#152]
Flow allows referencing types from other file with a syntax similar to ES6 imports: http://flowtype.org/blog/2015/02/18/Import-Types.html. These types (just like any other flow declarations) have no effect on runtime.

However, it seems like `babelify` doesn't prevent `browserify` from fetching and including modules referenced in this way. Expected behaviour would be to ignore `import type` statements.

```
$ echo "import type {Type1} from 'my-lib'" | ./node_modules/.bin/browserify -t [ babelify --plugins [ transform-flow-strip-types ] ] -
Error: Cannot find module 'my-lib' from '/my-project'
    at /my-project/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/my-project/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/my-project/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/my-project/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/my-project/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /my-project/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Tested with latest versions:
```
  "devDependencies": {
    "babel-plugin-transform-flow-strip-types": "^6.1.18",
    "babelify": "^7.2.0",
    "browserify": "^12.0.1",
```

**Comment by zertosh** [comment]
Works for me https://gist.github.com/zertosh/5a08b2eedb46c602550c. I think something is broken in browserify 12.0 with reading from stdin - but that's independent of babelify.

**Comment by mhagmajer** [comment]
@zertosh, thanks for your response!

I omitted the bug when minifying my example. Please try

```
./node_modules/.bin/browserify -t [ babelify --presets [ es2015 react ] ] entry.js
```

with latest versions as well

```
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
```

**Comment by zertosh** [comment]
This is a babel issue. https://github.com/babel/babel/issues/3084#issuecomment-157130889
