### ISSUE TITLE
Transpiling a project that imports modules from a project located under node_modules folder does not work

### ISSUE THREAD

**Issue by dcefram** [babel/babelify#153]
If I try to transpile a project that imports modules from a project located under node_modules folder, it does not simply work and would throw this quite common error: 

```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
```

The weird thing is that if I move the project from node_modules to the root folder (same level as node_modules folder), babelify simply works. To further understand what the heck I'm talking about, I'll just add this up:

This does not work:
```
myproject
  |
  | - node_modules
  |           |- the_project_I_include (es2015 modules)
  | - index.js
  | - gulpfile.js
```

This works:

```
myproject
  | - the_project_I_include
  | - node_modules
  | - index.js
  | - gulpfile.js
```

If I move it under bower_components, it would still work. 

I can't come up with any reason as to why it shouldn't work if it is located under node_modules. I tried searching for any similar issue, but I can't find any (yet, or I'm just plain blind)

If anyone can help, that'll be great. But as of now, I'm resorting to adding the es2015-based project that I include to bower.

**Comment by zertosh** [comment]
https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed

**Comment by dcefram** [comment]
Thanks, I tried adding
```
{
  "browserify": {
    "transform": [["babelify", { "presets": ["es2015"] }]]
  }
}
```
to the package.json of the modules that I wanted to transform, but it did not work.
did not work.

Running babelify as a global transform worked though, so I guess that's enough :) Thanks for pointing it out. (sorta dumb, I didn't read the FAQ section thoroughly)

**Comment by davidchase** [comment]
@dcefram i ran into a similar issue where my `const` werent being transformed when they were in the `node_modules` directory so my structure looked like:

```js
project
| - node_modules
    | - utils
         |- package.json (stuff that didnt get transformed)
```
adding `"only": "node_modules/**"` to the modules package.json seemed to have resolved the issue

```json
{
  "browserify": {
    "transform": [["babelify", { "presets": ["es2015"], "only": "node_modules/**" }]]
  }
}
```

> package.json in node_modules/utils/
