### ISSUE TITLE
catch babel errors

### ISSUE THREAD

**Issue by marvinroger** [babel/babelify#160]
I just updated to Babel 6, babelify 7 and browserify 12 (I had babel 5, babelify 6 and browserify 11) and I have a gulp task defined like so:

```js
gulp.task('es6-7', 'Process ES6/7 files with sourcemap support', function () {
  return browserify('./app/js/app.js')
    .transform(babelify.configure({ presets: ['es2015', 'stage-3', 'react'] }))
    .bundle()
    .on('error', function (error) {
      console.log('error');
      errorHandler('es6-7')(error);
      this.emit('end');
    })
    .pipe(plumber(errorHandler('es6-7')))
    .pipe(source('app.js'))
    .pipe(buffer())
    .pipe(sourcemaps.init({ loadMaps: true }))
    .pipe(uglify())
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('./public/js'))
    .on('end', browserSync.reload);
});
```

The `on('error')` was working fine in case of an error in the to-be-babelified js. Now, after the update, the error is not catched at all, the task continues to run.

Do you have any idea of what is going on ?

Thanks!

**Comment by zertosh** [comment]
Looks fine on the surface. Can you make a repo with a minimal repro case?

**Comment by marvinroger** [comment]
Nevermind, I tried to trigger an error with an `sfopzkeopfzeopf` line, but this is not illegal js, it's only an undefined variable, which is not illegal.

Sorry for the noise!
