### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by MoOx** [babel/babelify#161]
There is currently no CHANGELOG or no informations in github releases (tags). That does not offer an good UX.
I am using babel 5.8 (because there is still too many issue with babel ecosystem with 6.x) and I have no idea which version to use.

**Comment by zertosh** [comment]
The babelify 6.x versions are all babel 5. The babelify 7.x versions are all babel 6. But yeah, I should keep a changelog - sorry.

**Comment by zertosh** [comment]
Are there any issues in babelify 6.x that you're having? If it's something big, I don't mind making a release for it.

**Comment by MoOx** [comment]
babelify 6.x was working. Anyway, I am switching the project to webpack :)
