### ISSUE TITLE
babelify and async/await support

### ISSUE THREAD

**Issue by qspencer** [babel/babelify#162]
Hi, 

I'm trying to get babelify to work with the ES7 async/await syntax. My understanding is that I need to include the plugins "syntax-async-functions" and "transform-regenerator" to get this to work. I am currently enabling the presets "es2015" and "react". Note that the "es2015" preset includes the "transform-regererator" plugin. My package.json looks like this:
  "browserify": {
    "transform": [
      ["babelify", {"presets": ["es2015", "react"]}, {"plugins": "syntax-async-functions"}],
      "envify"
    ]
  }

I installed the presets and plugins via npm and confirmed by inspecting my "node_modules" folder that they were installed correctly. My other es6 code is being parsed by babelify, I just get an error when it encounters the "async" keyword in this code:

    async componentDidMount() {
        var _view = await this.ViewUtilities.loadNextView({currentView:this.state.view, baseURL:this.props.baseURL});
        this.setState({view: _view});
    }

Thank you in advance for insight into this problem.

**Comment by zertosh** [comment]
`babel-preset-es2015` includes "transform-regenerator" but with [async off](https://github.com/babel/babel/blob/v6.3.17/packages/babel-preset-es2015/index.js#L22). You can either (1) keep using "es2015" and add "transform-regenerator" to `plugins` (you'll be doing two passes), or (2) not use a preset, instead list out all the plugins you want.
