### ISSUE TITLE
Ignores files required from node_modules, causes problems when using npm link

### ISSUE THREAD

**Issue by codyrushing** [babel/babelify#164]
When using browserify, I usually `npm link` my local app folder to my project - that way I don't have to use relative paths in my require lookups.  This allows me to do `require("app/whatever")` instead of `require("../../../whatever")`.

However, when I require my files from the symlink in node_modules, babelify won't apply my presets.  Consider this basic example:

``` javascript
// node
var babelify = require("babelify");
var browserify = require("browserify");
browserify({
	entries: "test.js",
	debug: true,
	extensions: [".jsx"]
})
.transform(babelify, {presets: ["react"]})
.bundle();
```
``` javascript
// testComponent.jsx
var React = require("react");
module.exports = React.createClass({
    render: function(){
        <p>hello from react</p>
    }
});
```
``` javascript
// test.js
require("app/testComponent");
```
When I try to build the bundle using the above node code, I get a JSX syntax error on testComponent.jsx, meaning Babelify did not transpile the JSX.  However if I require the file using a relative path:
``` javascript
// test.js
require("./testComponent");
```
It transpiles the JSX no problem.  It looks like maybe Babelify doesn't transpile files that it thinks are external, which I suppose makes sense, but you should be able to transpile files from node_modules.

**Comment by jmm** [comment]
Hello @codyrushing. That's a Browser if my issue. See https://github.com/babel/babelify/blob/master/README.md#why-arent-files-in-node_modules-being-transformed. If you don't like the solutions there you can try my pathmodify plugin. There's a section in the README about the symlink scenario. You didn't say what version of Browserify you're using, but not that there have also been some recent bugs / changes to handling of symlinks there.

**Comment by zertosh** [comment]
Thanks @jmm!
