### ISSUE TITLE
Add only option to readme

### ISSUE THREAD

**Issue by davidchase** [babel/babelify#165]
In the section talking about `package.json` transforms:
> Why aren't files in node_modules being transformed?

I think it may help to add the `only` option to `node_modules` it seems like without it the transform doesn't not work on files in directories within the `node_modules` directory

For example my directory:

`/src/node_modules/app/lib/package.json`

without the only option set like so:
```js
{
  "browserify": {
    "transform": [["babelify", { "presets": ["es2015"], "only": "node_modules" }]]
  }
}
```

my `const` didn't transpile to `vars`... im not 100% but it seems the issue my lie in [here](https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js#L92-L93)

thoughts?

**Comment by zertosh** [comment]
Hmm... babelify doesn't go through babel-register so that's not it. In your example, is "app" a symlink to something in "src"?

**Comment by davidchase** [comment]
Its not a symlink they app is a directory within `node_modules`

**Comment by zertosh** [comment]
And you run browserify from `/src/node_modules/app`?

**Comment by davidchase** [comment]
so i run browserify from `src` which has its own `package.json` and the `node_modules` directory has the `app` which is my utils other things that i require ie `require('app/lib/utils')` so i have a package.json in each of my modules folder as if they were pulled from npm.


moreover i have test by removing the filename from [here](https://github.com/babel/babelify/blob/master/index.js#L18) as a test and then everything is working as expected as well as just using the basename of the file... and that also works.

which lead me to believe that babel does not like `node_modules` directory

**Comment by zertosh** [comment]
@davidchase is this is still an issue?
