### ISSUE TITLE
`.pipe(fs.createWriteStream("bundle.js"));` is not very user-friendly

### ISSUE THREAD

**Issue by worldsayshi** [babel/babelify#166]
In the main readme example you pipe the bundled content to `fs.createWriteStream("bundle.js")`.

Now it took me a while to realize why my build script just failed silently. As I understand it using createWriteStream this way will cause errors to be discarded (at least for my set up). Would be better to perhaps have something like this as an example?

```
var fs = require("fs");
var browserify = require("browserify");
browserify("./script.js")
  .transform("babelify", {presets: ["es2015", "react"]})
  .bundle(function (err, buf) {
    if (err) {
      console.log(err.message);
      return;
    }
    fs.writeFile("bundle.js",buf);
  });
```
Above is adapted from my own code so it might contain errors. I use watchify in my code as well.

**Comment by worldsayshi** [comment]
Here is an example with cleaner/more useful output:

```
var fs = require("fs");
var browserify = require("browserify");
browserify("./script.js")
  .transform("babelify", {presets: ["es2015", "react"]})
  .bundle(function (err, buf) {
    if (err) {
      console.log(err.message);
      return;
    }
    fs.writeFile("bundle.js",buf);
  });
```

(Adapted from my own code so it might contain errors)

**Comment by zertosh** [comment]
Streams are idiomatic in browserify, and a core part of node. Anyone can use whatever method they like.  

Strange though that it "just failed silently". If there is an error in the stream, and there is no `error` handler, then your application should've crashed.

**Comment by worldsayshi** [comment]
`Streams are idiomatic in browserify` - I'm not sure how to build an example that actually handle errors using streams, that's why I didn't use that.

**Comment by zertosh** [comment]
This is a really good streams guide: https://github.com/substack/stream-handbook

**Comment by zertosh** [comment]
Closing this out since it's more about an idiom preference.
