### ISSUE TITLE
Fix example command in Readme.md

### ISSUE THREAD

**Issue by singhshashi** [babel/babelify#168]
The CLI example under Usage given is 

$ browserify script.js -o bundle.js \
  -t [ babelify --presets [ es2015 react ] ]

However, having the square brackets in this command makes it fail. I am not quite sure why the square brackets between -t and babelify are given. Also what is the use of the escape sequence. However these are the errors that I get when I run different variations of the command.

>
Command: browserify app.jsx -o bundle.js \ -t [babelify --presets [es2015,react]]
Error: Cannot find module '/home/shashi/WebstormProjects/MyReactBox/ -t' from '/home/shashi/WebstormProjects/MyReactBox'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)

>
Command: browserify app.jsx -t [babelify --presets [es2015,react]] -o bundle.js 
Error: ParseError: 'import' and 'export' may appear only with 'sourceType: module'

This works
>browserify app.jsx -t babelify --presets [es2015,react] -o bundle.js 

I lost a lot of time wondering why something as simple as given in the Readme was not working. :(

**Comment by zertosh** [comment]
Browserify uses [subarg](https://github.com/substack/subarg) to parse arguments, and it uses the square bracket notation.

> Also what is the use of the escape sequence.

Vanity. The line was too long and github made you horizontally scroll.

> However these are the errors that I get when I run different variations of the command.

Try: `browserify app.jsx -o bundle.js -t [ babelify --presets [ es2015 react ] ]`. I think the spaces between the brackets are significant.

**Comment by zertosh** [comment]
I removed the escape from the README. Can you confirm if that fixes your issue?

**Comment by singhshashi** [comment]
Yes, it does. As you said, the spaces between the brackets are significant as well.
