### ISSUE TITLE
Weird error: module not found

### ISSUE THREAD

**Issue by LeXtruX** [babel/babelify#169]
when I do the following:
`browserify index.js -o bundle.js \ -t [ babelify ]`
I get this error:
`E:\NATA\lib>browserify ./index.js -o bundle.js \ -t [babelify]
Error: Cannot find module 'E:\' from 'E:\NATA\lib'
    at C:\Users\Stijn'LeXtruX'\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\Stijn'LeXtruX'\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Stijn'LeXtruX'\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Stijn'LeXtruX'\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)`

The browserify works fine when not using the `-t [babelify]`

**Comment by singhshashi** [comment]
I think the example command given in the documentation is wrong as I also faced a similar error. 

Try the following command
```
browserify index.js -o bundle.js -t babelify --presets[es2015,react]
```
If you have specified presets in your .babelrc file, you could leave that option I think. 

I already created an issue https://github.com/babel/babelify/issues/168 for fixing the Readme.

**Comment by zertosh** [comment]
I removed the escape from the example. Have you tried `browserify index.js -o bundle.js -t [ babelify ]`?

**Comment by zertosh** [comment]
Any luck?

**Comment by LeXtruX** [comment]
not yet, I have postponed the development and I'm learning Node.js the proper way right now
