### ISSUE TITLE
Multiple _classCallCheck and other functions output with browserify

### ISSUE THREAD

**Issue by vekexasia** [babel/babelify#170]
Hello there,

I'm using browserify + babelify to compile a set of classes. Every class gets compiled but the _classCallCheck, _possibleConstructorReturn, _inherits (etc) functions are being regenerated every time adding considerable boilerplate.

Is there a way to declare these babel utilities just once and reuse them for subsequent class declarations?

**Comment by zertosh** [comment]
See http://babeljs.io/docs/plugins/transform-runtime/ and http://babeljs.io/docs/plugins/external-helpers/

**Comment by vekexasia** [comment]
Hello @zertosh Sorry to bother you again. I tried to read those links but they're not explaining anything about how and what they do.

I tried to read the code and I may understand the transform runtime but external helpers is quite obscure to me. Probably due to my lack of knowledge on the babel platform. 

Can you help me out and point me in the right direction on why i may need external-helpers and what the heck it is used for? Thank you ! :)

**Comment by zertosh** [comment]
http://www.2ality.com/2015/12/babel6-helpersstandard-library.html#the-helpers-via-a-global-variable-babel-plugin-external-helpers-2
