### ISSUE TITLE
Breaks Browserify's require() method

### ISSUE THREAD

**Issue by ericbiewener** [babel/babelify#175]
I am unable to use `require('../path/to/file.js')` after Babelify transforms my code. It appears that the `require()` method is no longer the one required to make that syntax work. Instead, whatever undesired `required` method has taken its place always returns either an empty object `{}` or `undefined`.

If, however, I add `require = window.require` to the top of the page, then everything works fine. To be clear, Browserify was working fine prior to adding the Babelify transform.

I first encountered this when using `require()` in my own code. Trying to use something like `React = require('react')` is resulting in `React` being undefined. I posted on StackOverflow about it [here] (http://stackoverflow.com/questions/34839456/using-babelify-to-compile-react-results-in-react-router-being-undefined/34965407#34965407), thinking that I found the answer in simply switching to ES2015's `import` syntax. However, I am now getting the same error in a node package that is using the `require` syntax. Specifically, I'm using the [ffmetadata] (https://www.npmjs.com/package/ffmetadata) package. It's main `index.js` file begins with the following:

```
var spawn = require("child_process").spawn,
	ffmpeg = spawn.bind(null, process.env.FFMPEG_PATH || "ffmpeg"),
```

That second line throws the error:

`Uncaught TypeError: Cannot read property 'bind' of undefined`

The `spawn` variable is undefined. For some slight debugging, I logged the value of `require("child_process")` to the console, which resulted in an empty object `{}`.

In poking around further, I realized that I could paste those two lines of code directly into my console and they'd work fine. This is how I discovered that the desired global `require()` method was not the one actually getting used. As I said earlier, putting `require = window.require` at the top of the necessary files solves the issue.

In case it helps, I am using Browserify via gulp, with the following code:
```
gulp.task('js', function() {
	var browserify = require('browserify'),
			watchify   = require('watchify'),
			babelify   = require('babelify');

	function bundle() {
		b.bundle()
			.on('error', function(error){
				gutil.log(error);
			})
			.pipe(source('app.js'))
			.pipe(gulp.dest(paths.client.js.build))
	}

	var b = browserify({
		cache: {},
		packageCache: {},
		entries: paths.client.js.dev,
		debug: true,
		plugin: [watchify]
	})
	.transform(babelify, {presets: ['es2015', 'react']})

	b.on('update', function(){
		bundle();
	});

	b.on('log', gutil.log);
	bundle();
});
```

**Comment by loganfsmyth** [comment]
Browsers have no concept of child processes. That is failing for the exact reason it says, there is no `spawn` function that will run in a browser.

Closing since this is not babelify related, but feel free to see the Babel readme for suggested support channels for Babel questions: https://github.com/babel/babel#looking-for-support

**Comment by ericbiewener** [comment]
Sorry about that misleading code -- I was writing it for an Electron app, which does in fact provide the child_process (and everything else in node) to the app. As I mentioned, the same thing happens when trying to `require()` react as well. I actually posted about this on StackOverflow [here] (http://stackoverflow.com/questions/34839456/using-babelify-to-compile-react-results-in-react-router-being-undefined/34965407#34965407) a little while back when building an app *not* in Electron, but just a standard web app.

So I'm getting the same result when building a standard web app, and when trying to `require` a front-end node module like React.

**Comment by loganfsmyth** [comment]
@ericbiewener I don't know much about Electron specifically, but if you're running your code through Browserify, you're getting Browserify's implementations `require` and it's browser replacements for of every module you use, including `child_process`.

**Comment by TomHarker** [comment]
Why can't the tool just package up the JS? Let the platform worry about its execution.
