### ISSUE TITLE
import with symlink throws ParseError

### ISSUE THREAD

**Issue by marlun78** [babel/babelify#176]
I’m trying to use symlinks to avoid `import x from '../../../../../../file.js'` as suggested in the [Browserify Handbook](https://github.com/substack/browserify-handbook#avoiding-). This gives me a ParseError. Is this due to an issue with babelify?

```
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

See how to reproduce: https://github.com/marlun78/linked

Thanks!

**Comment by loganfsmyth** [comment]
By default, Browserify transforms do not run on files inside `node_modules`. That error is because Babelify isn't running on your utils at all. Not sure what the normal approach would be for something like this. Probably worth asking in Browserify's support channels.

**Comment by zertosh** [comment]
Try https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed
