### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by ericandrewlewis** [babel/babelify#177]
I installed babelify, browserify, and the babel-preset-es2015 packages in preparation for transpiling source code.

Here's my `package.json`

```javascript
{
  "name": "prosemirror-experiments",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-preset-es2015": "^6.3.13",
    "babelify": "^7.2.0",
    "browserify": "^13.0.0",
    "prosemirror": "^0.1.1"
  }
}
```

After that I try to run the browserify command as describe in the readme `node_modules/.bin/browserify src/index.js --outfile dist/index.js -t babelify --presets es2015` but get an error
```bash
# node_modules/.bin/browserify src/index.js --outfile dist/index.js -t babelify --presets es2015

/Users/206096/Desktop/prosemirror-experiments/src/index.js:1
import { ProseMirror } from "prosemirror/dist/edit";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

If I add a `.babelrc` file like this
```javascript
{
  "presets": ["es2015"]
}
``` 
it works.

**Comment by loganfsmyth** [comment]
The README examples includes square brackets, you need to use them :)

**Comment by ericandrewlewis** [comment]
OH! I thought the brackets meant that those bits were optional, similar to what I've seen in man docs (maybe [Wirth syntax notation]?(https://en.wikipedia.org/wiki/Wirth_syntax_notation)).

Perhaps we should include an explicit reference in the CLI part of the readme noting that the brackets are required in the command.

**Comment by zertosh** [comment]
The square brackets notation is a browserify-ism. It comes its use of [subarg](https://github.com/substack/subarg).
