### ISSUE TITLE
ES7 support, babel 6

### ISSUE THREAD

**Issue by serheyShmyg** [babel/babelify#179]
Hello.
How to enable es7 decorators?
Or any other experimental feature?

**Comment by zertosh** [comment]
Babelify takes the same options that you'd pass to babel.

**Comment by serheyShmyg** [comment]
@zertosh When I pass transform-decorators-legacy plugin, it not work. But if I add .babelrc and add this plugin there, everything is fine.

**Comment by zertosh** [comment]
@serheyShmyg Can you provide a small repo that I can use to reproduce your issue?

**Comment by loganfsmyth** [comment]
@serheyshmyg you are probably hitting https://github.com/babel/babel/pull/3348

**Comment by zertosh** [comment]
Seems resolved!
