### ISSUE TITLE
`require` retrieves an empty object instead of exported value

### ISSUE THREAD

**Issue by brycehanscomb** [babel/babelify#183]
I've got a file called `IN.js`:

``` js
// IN.js

module.exports = 5;
```

Which gets transpiled with this command by babelify (as per the CLI instructions [here](http://babeljs.io/docs/setup/#browserify)):

```
browserify IN.js -t babelify --outfile OUT.js
```

My `OUT.js` contains this:

``` js
// OUT.js

(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";

module.exports = 5;

},{}]},{},[1]);

```

Te problem is when I try to make use of this module via `require`, the following `TEST.js` file shows an unexpected result:

``` js
// TEST.js

const testVal = require('./out'); // should be 5

console.log(testVal);
// --> {}
```

Unfortunately, it logs out an empty object (`{}`). Am I doing it right expecting `testVal` to be `5`?

PS: my `package.json`'s `devDependencies` looks like this:

``` json
"devDependencies": {
    "babel-cli": "^6.5.1",
    "babel-preset-es2015": "^6.5.0",
    "babelify": "^7.2.0"
  }
```

and my `.babelrc` looks like this:

``` json
{
  "presets": [
    "es2015"
  ],
  "plugins": []
}
```

**Comment by loganfsmyth** [comment]
This isn't really related to Babel. The point of browserify is that it bundles up everything, you don't generally use it to create a bundle that you'd load via `require`. The `OUT.js` file is meant to be loaded via `<script>`, it is not a module on its own (not by default anyway).

So normally you'd `require` the non-browserified files from `TEST.js` and then run `browserify` on _that_.

**Comment by brycehanscomb** [comment]
My use case is packaging up an ES6-authored module for publishing on npm. Because of the new `exports.default` behaviour from Babel 6, my transpiled code (`import` -> `require()`) doesn't point to the right object reference by default.

The reason I posted the issue here is because this test case works for me with browserify pure, and babel pure, but not through the `babelify` command as posted on the babel website.

**Comment by zertosh** [comment]
@brycehanscomb the option you're missing is the browserify's [`standalone`](https://github.com/substack/node-browserify#browserifyfiles--opts). A browserify bundle just runs - doesn't return or export anything. The empty object you're seeing is from node's module wrapper. When you use the `standalone` option, then you can require that bundle and get the export of the entry file.

**Comment by canastro** [comment]
@brycehanscomb were you able to fix this?

**Comment by loganfsmyth** [comment]
@canastro Are you using the standalone option mentioned in the comment above yours?

**Comment by canastro** [comment]
Yes, I had a module published to npm (module A) with a standalone bundle with babelify.
When creating module B, i added module A as a dependency.

When requiring module A I get a error in the places where it tries to require local files (like `./file2`).

**Comment by AionDev** [comment]
i was having the same behavior - and just realized what was wrong. 
I was publishing my bundled version of the package to npm - instead of plain old modules..

So in order to publish that package - just have the `package.json` and the `src files` - do not bundle anything, and it will work.

**Comment by stirredo** [comment]
I was able to fix my issue by using require() instead of using import statements.

**Comment by renatorroliveira** [comment]
So we can't use import/export syntax for publishing modules? I thought I could write ES6 with import/export and transpile using `babel`command. Publishing those transpiled versions should work... at least I thought it should. But it doesn't, Node.js at least don't "see" the exports.default (transpiled file, generated from `export default` syntax) on the script that requires it...

Is there any thing I can do to make babel use old module.exports syntax on transpiled files?
