### ISSUE TITLE
Possible to set the BABEL_ENV via options?

### ISSUE THREAD

**Issue by bluejamesbond** [babel/babelify#184]
We have multiple babel environments; anyway to allow babelify to modify that value?

I made a fork with a simple edit for that support (not sure how env affects the default presets...merge or override?):
https://github.com/bluejamesbond/babelify/commit/91d0aeddcf359148c330ea1a62b095463810b30d

Usage: 
```
transform: [['babelify', {env: 'client'}]]
```

**Comment by zertosh** [comment]
I'm afraid that mucking with the environment like that is not something I'd like to support. However, in your fork, I recommend that you change the env immediately before `var result = babel.transform(this._data, this._opts);` and then set it back immediate after it. Where you have it now, you're susceptible to race conditions. There's no guarantee that any other babelify you may have running isn't going to change the `BABEL_ENV` before the `_flush` is called.
