### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by ld0rman** [babel/babelify#187]
**Environment:** `node@5.70` `npm@3.75` `browserify@13.0.0` `babelify@7.2.0`

Trying to build an app that worked with `npm@2` and `babelify@6` but having problems upgrading to `npm@3` and `babelify@7`. Allow me to try and explain the problem.

- In `app/node_modules` I have modules installed via `npm install` and local modules symlinked via `npm link`. 

- The local modules have browserify transforms specified in their `package.json` e.g -

```json
...
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.5.0",
    "babelify": "^7.2.0"
  },
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "es2015"
          ]
        }
      ]
    ]
  }
...
```
Attempting to build I get error:

`"Browserify Error: Couldn't find preset "es2015" relative to directory"`

But under `app/node_modules` there are all the packages relating to `babel-preset-es2015`. 

It's as if babelify is looking under `app/node_modules/symlinked-module/node_modules` for the presets, but as npm@3 has flattened out the dependency tree, it will only find them if it walks up the this tree. I thought that this was the automatic behaviour but obviously not or I wouldn't be getting this error. Is this a browserify problem or an babelify problem? Any help would be much appreciated.

**Comment by ld0rman** [comment]
Could this have something to do with [this issue](https://github.com/substack/node-browserify/issues/1359)

**Comment by ld0rman** [comment]
I think this is a browserify problem so I will close this issue. Will re-open if I'm mistaken

**Comment by dongtong** [comment]
@ld0rman Did you fixed this issue?

**Comment by ld0rman** [comment]
Not really - babel requires its plugins to be in the same directory and there doesn't seem to be much will to change this
