### ISSUE TITLE
No such file or directory, if dest file is in a directory that does not exist.

### ISSUE THREAD

**Issue by ethyde** [babel/babelify#188]
Hi,

I try to use Babelify with npm script with the following command : 
```
"scripts": {
    "build": "browserify app/scripts/main.js -o build/scripts/main.js -t [ babelify --presets [ es2015 ] ]"
  }
```
But if ```build/scripts/``` folders does not exist i have this error : 
```
Error: ENOENT: no such file or directory, open 'build\scripts\main.js' at Error (native)
```

So what is the problem ? 

Thanks ! :)

**Comment by zertosh** [comment]
does `build/scripts` exist? browserify won't create directories for you.

**Comment by ethyde** [comment]
Ah , ok, I don't find anything about it in the docs .

But it is possible to do so? And how ? Or should I use another package or a workaround ?

Thanks.

**Comment by zertosh** [comment]
Make the directory before running browserify: `mkdir -p build/scripts && browserify ...`

**Comment by ethyde** [comment]
It's work, thanks a lot ! :)
