### ISSUE TITLE
ES6 assignment/arrow sign not recognized?

### ISSUE THREAD

**Issue by Captain1** [babel/babelify#189]
browserify news.js -o bundle.js -t [ babelify --presets [ es2015 react ] ]
![screenshot from 2016-03-07 16 31 11](https://cloud.githubusercontent.com/assets/4882809/13575710/29a1925e-e482-11e5-959e-3803475ab80f.png)

**Comment by loganfsmyth** [comment]
Not obvious, but the error is the equal sign, not related to the arrow. Looks like you are trying to use https://babeljs.io/docs/plugins/transform-class-properties/ but have not enabled it.

**Comment by hzoo** [comment]
like logan mentioned, you'll need to add the class-properties plugin or enable the stage 2 preset as well (you only have es2015 + react)
