### ISSUE TITLE
Add options to silence the plugin

### ISSUE THREAD

**Issue by gabipetrovay** [babel/babelify#190]
I would like to be able to make the plugin more quiet:

```shell
browserify -t [ babelify --presets [ es2015 react ] --quiet ]
```

or the node equivalent:

```js
b.transform(babelify, { presets: ['es2015'], quiet: true });
```

or using a log level.

Is this currently possible?

**Comment by zertosh** [comment]
Babelify mostly just a passthrough to babel. So unless babel supports "quiet", any solution would be super hacky.
