### ISSUE TITLE
Babelify not converting dependencies

### ISSUE THREAD

**Issue by csarven** [babel/babelify#199]
There is a library that I use as a dependency (https://github.com/simplerdf/simplerdf).
When I use babelify with browserify, it fails to convert it from es6 to es5.

Is babelify meant to convert dependencies?
Or should the simplerdf library be released in es5?

/cc @bergos @nicola

**Comment by jmm** [comment]
By default babelify, as with any browserify transform, [won't transform modules in `node_modules`](https://github.com/babel/babelify/tree/6d45fa84762f3b57a4b7bef0e1bbdf484614f74d#why-arent-files-in-node_modules-being-transformed) unless that module is part of a package that configures a transform in `package.json`. You've installed this package from npm and it's published as ES6?

**Comment by nicola** [comment]
Hey @jmm, simplerdf is published in es6, is there something I should add in my package json to transform it?

**Comment by nicola** [comment]
Would this work?
https://github.com/simplerdf/simplerdf/pull/46

**Comment by jmm** [comment]
Hey @nicola. If you are going to go with that approach you'd need to make the transform (`babelify`) and anything it requires (e.g. `babel-preset-es2015`) a dependency, not a devDependency. I think it'll work with passing the options to the transform like you have it (the alternative would be to put that config in a `.babelrc` or under a `babel` prop in `package.json`).

That being said it may be simpler to just publish ES5. For one thing, while this would address browserify, it won't address other module bundlers like webpack. I don't know how webpack handles that, but by publishing ES5 it wouldn't be an issue.

**Comment by nicola** [comment]
hey @jmm thanks,
this really makes sense, I will do that then.

Thanks for the explanation!

**Comment by jmm** [comment]
Ok @nicola, you're welcome. @csarven I'm closing this issue because there's nothing specific to babelify about this situation. It's the way browserify transforms work in general, but more importantly it's an effect of how the dependency is published.

**Comment by stevenvachon** [comment]
Use the `--global-transform` option instead of `--transform`.
