### ISSUE TITLE
Unexpected token (12:17) while parsing file: testReducer.js

### ISSUE THREAD

**Issue by tobiasmuecksch** [babel/babelify#201]
This is my gulp task:

```
	gulp.task("babel", function (callback) {
		var bundler = browserify({
			entries: 'src/app.js',
			debug: true
		});
		bundler.transform(babelify.configure({
			presets: ["es2015", "react"]
		}));

		bundler.bundle()
			.on('error', function (err) { console.error(err); })
			.pipe(source('app.js'))
			.pipe(gulp.dest('dist'));
	});
```

When I run `gulp babel` I receive an `Unexpected token while parsing file` error. [Here is the full error stack tace](http://pastebin.com/NPeewuWS).

The respective line 12 looks like this:

`var helpme = {...state[i], likes: state[i].likes + 1};`

For some reason changing the line to `var helpme = [...state[i]];` works and the compilation runs without errors.

[Here is my full testReducer.js](http://pastebin.com/icA75XuS)

_(Side-Question: Why the hack does the error not show what exact token/character was unexpected?)_

**Comment by jmm** [comment]
Hello @tobiasmuecksch, you're using object spread syntax without a plugin for it. [transform-object-rest-spread](http://babeljs.io/docs/plugins/transform-object-rest-spread/) or stage 2 preset.

**Comment by tobiasmuecksch** [comment]
@jmm Thank you for the quick reply. Sorry for opening a useless issue.

**Comment by jmm** [comment]
@tobiasmuecksch You're welcome. In the future if you're not sure you've isolated a bug you might want to try Babel's Slack. You might even get help quicker.
