### ISSUE TITLE
Speed up gulp file for dev mode with prevent import/export from es6.

### ISSUE THREAD

**Issue by mitorski** [babel/babelify#202]
So... I have diffrent tasks for development and production mode of gulp.

```
gulp
    .watch(
      jsPaths.src
    )
    .on('change', (file) => {
      process.env.filepath = file.path;
      process.env.filename = file.path.split('/').pop();
      gulp.start('scripts-dev');
    });
```

```
gulp.task('scripts-dev', () => {
  let filename = process.env.filename,
    filepath = process.env.filepath;
  return browserify(
    {
      entries: filepath,
      debug: false
    }
  )
    .transform("babelify", {presets: ["es2015"]})
    .bundle()
    .on('error', handleError)
    .pipe(
      source(filename)
    )
    .pipe(
      buffer()
    )
    .on('error', handleError)
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError())
    .pipe(
      connect.reload()
    )
    .pipe(
      gulp.dest(jsPaths.dest)
    );
});
```

And the question is... how can i prevent import/export with signle file compile.

```
import layout   from './layout/layout.module';
import example  from './example_module/example.module';

let modules = [
  'layout',
  'example'
];

export default modules;
```

If i have this pices of code, then babel compile all import files too, and this is not in my intereses for this moment. Can i do something for this?

I was research the internet since last two day for good way in compile all files separated without success and it's my last idea for do it.

Can someone explain me how it work?

**Comment by loganfsmyth** [comment]
This isn't a question that's specifically Babel relate. You'd want to use `watchify` with an approach like this: https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md

**Comment by mitorski** [comment]
`function singleJs(){
  let c = {
    entries: [process.env.filepath],
    debug: true
  },
      o = assign({}, watchify.args, c),
      b = watchify(browserify(o));
  b.bundle()
    .on('error', gutil.log.bind(gutil, console.log('browserify error')))
    .pipe(source(process.env.filename))
    .pipe(buffer())
    .pipe(sourcemaps.init({loadMaps: true}))
    .transform("babelify", {presets: ["es2015"]}) // no idea if is needed
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest(jsPaths.dest));
}`

i dont see any difference.. still compile all from change file with own imports.

**Comment by loganfsmyth** [comment]
@mitorski The key part, which you haven't reproduced in your example, is that the `b = watchify(browserify(o));` part goes _outside_ your task, you only do it once, and then do the `.bundle()` part when your task runs.
