### ISSUE TITLE
Babel still used even when the ignore option says the file shouldn't be used.

### ISSUE THREAD

**Issue by fabiosantoscode** [babel/babelify#203]
We're using babelify together with browserify, and we've noticed that the ignore option isn't being respected by babelify. Babel is still called even in ignored files (we ignore node_modules), and when it finds that these files in node_modules have a package.json with options for Babel 5, it promptly crashes with an assertion error.

Looking at the code, it doesn't seem like the ignore option is used at all. Should Babel really be called in this situation?

**Comment by dwelle** [comment]
@fabiosantoscode the `ignore` is a [babel option](https://babeljs.io/docs/usage/api/), and it's passed to babel [here](https://github.com/babel/babelify/blob/6997ff5bec307269978545e5295b46fc9f399f42/index.js#L27).

**Comment by fabiosantoscode** [comment]
So maybe here babel can't understand that the file I'm compiling is inside another node_modules folder, as it finds the nearest .babelrc or package.json and bases the path upon it? Babel's ignore option usually works well for me

**Comment by dwelle** [comment]
Can't say, you'd have to paste your config and paths you're compiling.

**Comment by loganfsmyth** [comment]
Babel's `ignore` is unfortunately a little buggy. I'm not sure what you mean for `node_modules` though. Unless you've explicitly enabled `babelify` as a global browserify transform, it should never process `node_modules`.

**Comment by hzoo** [comment]
Yeah it defaults to not compiling node_modules, and babel-core v7 should fix some of the ignore issues
