### ISSUE TITLE
[es2016] 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by marvinosswald** [babel/babelify#205]
If i set **es2015** as preset everything works, with **es2016** it throws:

`'import' and 'export' may appear only with 'sourceType: module'`

maybe i'm missing a option here but i can't find anything tried setting it like:
``` js
options: {
     presets: ['es2016', 'react'],
     sourceType: "module"
}
```

**Comment by hzoo** [comment]
es2016 doesn't contain es2015 so you need both or if you only need modules use the commonjs plugin as well

**Comment by marvinosswald** [comment]
i see, thanks :)
