### ISSUE TITLE
global ignore configuration in package.json

### ISSUE THREAD

**Issue by jeromecovington** [babel/babelify#213]
I am attempting to transpile `jsdom` during my `babelify` transform, so that it can pass through `uglify` without errors. The path to `jsdom` within my app is `node_modules/@namespace/dependency-name/node_modules/jsdom`. Below is my `browserify` setup in my app's `package.json`. However it seems that babel is trying to enter all codepaths (it is erroring when it tries to transpile other project root level `node_modules` dependencies, which I am trying to ignore).

Does anyone have thoughts on how to better structure the `babelify` ignore configuration?

```
"browserify": {
  "extensions": [
    ".js",
    ".jsx"
  ],
  "transform": [
    [
      "babelify",
      {
        "global": true,
        "ignore": "\/node_modules\/(?!@namespace\/dependency-name\/)",
        "presets": [
          "es2015",
          "react"
        ],
        "plugins": [
          "transform-class-properties",
          "transform-async-to-generator",
          "transform-object-rest-spread",
          "transform-runtime",
          "../../../lib/utils/babelRelayPlugin"
        ]
      }
    ],
    [
      "envify"
    ]
  ]
}
```

**Comment by stevenvachon** [comment]
I'm also having issues with `global` and `ignore`. Sadly, this issue has not even been addressed by the babel team.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

**Comment by goto-bus-stop** [comment]
FWIW the reason for this is that `{ global: true }` does not work in package.json, only in the Node API and on the CLI using `-g`. It cannot be addressed by Babel, and is intentional behaviour on part of browserify.
