### ISSUE TITLE
Add way to detect that babel plugin is running in browserify.

### ISSUE THREAD

**Issue by DylanPiercey** [babel/babelify#214]
Currently I cannot find a way to tell if my module is being built for the browser or the server.
Typically if something is being built with browserify or webpack I can assume that it is for the browser and I can do browser specific transforms (such as https://github.com/DylanPiercey/isbrowser).

I was hoping we could add some (global?) flag that is set when running this and https://github.com/babel/babel-loader which could allow for plugins to know when the output is meant for the browser.

This could be useful for any sort of plugin that needs to know if the resulting build is for node js or the browser. Such as platform dependent shims, isomorphic code detection, asset inlining, etc.

**Comment by loganfsmyth** [comment]
This is now available in Babel 7.x via the `api.caller()` API in function config files: http://babeljs.io/docs/en/config-files#apicallercb

We'll be releasing a new version of `babelify` soon with support for now.
