### ISSUE TITLE
using Browserify with Babelify

### ISSUE THREAD

**Issue by rgolea** [babel/babelify#215]
Hi there! I know there are a lot of questions regarding this but the documentation is not working when trying to import `node_modules`.

This is my browserify task:

```
'use strict';

const gulp = require('gulp');
const browserify = require('browserify');
const source = require('vinyl-source-stream');
const gulpif = require('gulp-if');
const buffer = require('vinyl-buffer');
const uglify = require('gulp-uglify');
const rename = require('gulp-rename');
const babelify = require('babelify');

gulp.task('browserify', () => {
    return browserify(global.files.js.source)
        .transform(babelify, {
          "presets": [require('babel-preset-es2015'), require("babel-preset-stage-0")],
          "only": [global.files.js.folder, "/node_modules/**/*"]
        })
        .bundle()
        .pipe(source(global.files.js.build))
        .pipe(gulpif(global.release, buffer()))
        .pipe(gulpif(global.release, uglify()))
        .pipe(gulpif(global.release, rename(global.files.js.release)))
        .pipe(gulpif(global.release, gulp.dest(global.RELEASE_FOLDER), gulp.dest(global.BUILD_FOLDER)))
        .pipe(gulpif(global.browserSync, global.browserSync.stream()));
});

gulp.task('browserify:watch', ['browserify'], () => gulp.watch([`./${global.SRC_FOLDER}/**/*.js`, `./${global.TMP_FOLDER}/**/*.js`], ['browserify']));

module.exports = gulp;
```

Still, somehow I can't seem to transpile the code that comes from `node_modules` properly. Any ideas?

**Comment by AgentME** [comment]
Browserify doesn't apply transforms to files under node_modules by default. The second parameter to `.transform` has to have `global: true` in order for the transform to run on files under node_modules.

Note that a lot of modules may not work with babel transpilation. Babel by default forces strict mode, it doesn't allow top-level `this` within modules, and some modules may have old .babelrc files that aren't compatible with Babel 6 and aren't meant to be used by consumers.

**Comment by hzoo** [comment]
Yeah no node_modules compliation by default, we have fixed the issue ^ regarding strict module in babel v7
