### ISSUE TITLE
Support async without plugin

### ISSUE THREAD

**Issue by timwis** [babel/babelify#218]
I'm using [budo](https://github.com/mattdesl/budo) which uses babelify under the hood. I'm targeting modern chrome browsers, which supports async/await out of the box today (as far as I know), so I don't need to transpile those tokens. But it appears to be failing on the babelify step, throwing "Unexpected token" on "async". Is there any way to get babelify to recongise this token without transpiling it?

**Comment by hzoo** [comment]
use preset-env

**Comment by timwis** [comment]
@hzoo I imagine you're plowing through a ton of open issues, but I wanted to (constructively) let you know that your reply came off as rather curt, particularly considering it came a year after my question was posted. Fortunately, I didn't wait for a reply and dug further into the problem a month afterwards, submitting [a handful of pull requests](https://github.com/browserify/browserify/issues/1667) to address this error.

**Comment by hzoo** [comment]
Sorry bout that, yep was just closing old issues 😄, no idea if this was already solved or not and people are thinking this package is not unmaintained or deprecated? I was just cleaning up old stuff so figured you already solved it, we haven't touched this package in a while
