### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module' error being thrown when I import from node_module dependency

### ISSUE THREAD

**Issue by inkorange** [babel/babelify#219]
My ES6 ReactJS application transpiles fine with imports local to the project. When I include a module installed to my node_modules directory, I get the famous **'import' and 'export' may appear only with 'sourceType: module'** error. 

Babel configuration using Browserify:

`bundler.transform(babelify.configure({presets: ["es2015", "stage-0", "react"]}));`

package.json:
```
...
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-es2016": "^6.16.0",
    "babel-preset-latest": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-0": "^6.5.0",
    "zebra-stripes": "file:///Users/cwest/web/Stripes/zebra-stripes-0.0.1.tgz"
...
```

This builds just fine:
```
"use strict"

import React from 'react'
import { render } from 'react-dom'

import {Icon} from '../Stripes/Symbols/Icon' // from local build
//import {Icon} from 'zebra-stripes/Symbols/Icon' // from node_modules


class StripesDemo extends React.Component {

    render() {
        return (
            <div>***</div>
        )
    }
}

module.exports = StripesDemo;
```

But when I use the same file, but referencing the one I installed into the node_modules folder, I get the import/export module error.

```
//import {Icon} from '../Stripes/Symbols/Icon' // from local build
import {Icon} from 'zebra-stripes/Symbols/Icon' // from node_modules

```
Same file, referenced 2 different ways.

Why do I get this error only when I import from node_modules? How do I go about fixing this one? Do I need to amend my package.json within my npm package?

**Comment by edwardcasbon** [comment]
Did you find a resolution to this? I'm having a similar problem.

**Comment by loganfsmyth** [comment]
This is documented here: https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed
