### ISSUE TITLE
Updated babelify(^7.3.0) causes "Unexpected token" error

### ISSUE THREAD

**Issue by elgskred** [babel/babelify#224]
My npm start script:  
"start": "browserify -t babelify --standalone main views/main.js -o public/main.js && node app.js"

This works with babelify "^6.3.0" but with a updated babelify(^7.3.0) causes Unexpected token at:

`module.exports = function (data, containerId) {`
`var container = document.getElementById(containerId || 'content');  `
 ` ReactDOM.render(  `
`    <Content {...data} />,  `
`    container  `
`  );  `
`};`

Specifically line 4 "<". 
If I'm to use the updated version, what do I need to change?

**Comment by hzoo** [comment]
you need the react-preset? Seems like it's not picking up `<` in JSX
