### ISSUE TITLE
Issue with .babelrc.presets( using gulp-babel), unknown option

### ISSUE THREAD

**Issue by sanjeev2315** [babel/babelify#225]
I am using babel 6.X versions and gulp. I am not able to run grunt serve, it gives the below error:-

    throw er; // Unhandled stream error in pipe.
    ^
ReferenceError: [BABEL] D:\Sapient_Learning_Path\client\app\app.constant.js: Un
kown option: D:\Sapient_Learning_Path\.babelrc.presets

Package.json

"dependencies": {
    "babel-runtime": "^6.18.0",
    "bluebird": "^2.9.34",
    "body-parser": "^1.13.3",
    "composable-middleware": "^0.3.0",
    "compression": "^1.5.2",
    "connect-mongo": "^0.8.1",
    "cookie-parser": "^1.3.5",
    "ejs": "^2.3.3",
    "errorhandler": "^1.4.2",
    "express": "^4.13.3",
    "express-jwt": "^3.0.0",
    "express-session": "^1.11.3",
    "jsonwebtoken": "^5.0.0",
    "lodash": "^3.10.1",
    "lusca": "^1.3.0",
    "method-override": "^2.3.5",
    "mongoose": "^4.1.2",
    "morgan": "~1.6.1",
    "passport": "~0.3.0",
    "passport-local": "^1.0.0",
    "passport-oauth2": "^1.3.0",
    "passport-wsfed-saml2": "^2.11.2",
    "request": "~2.72.0",
    "serve-favicon": "^2.3.0",
    "socket.io": "^1.3.5",
    "socket.io-client": "^1.3.5",
    "socketio-jwt": "^4.2.0"
  },
  "devDependencies": {
    "autoprefixer": "^6.0.0",
    "babel-cli": "^6.18.0",
    "babel-core": "6.21.0",
    "babel-preset-es2015": "^6.18.0",
    "chai": "^3.2.0",
    "chai-as-promised": "^5.1.0",
    "chai-things": "^0.2.0",
    "connect-livereload": "^0.5.3",
    "del": "^2.0.2",
    "gulp": "^3.9.0",
    "gulp-add-src": "^0.2.0",
    "gulp-angular-templatecache": "^1.7.0",
    "gulp-autoprefixer": "2.3.1",
    "gulp-babel": "^5.1.0",
    "gulp-cache": "^0.2.10",
    "gulp-concat": "^2.6.0",
    "gulp-env": "^0.2.0",
    "gulp-filter": "^2.0.2",
    "gulp-imagemin": "^2.2.1",
    "gulp-inject": "^1.3.1",
    "gulp-istanbul": "~0.10.3",
    "gulp-istanbul-enforcer": "^1.0.3",
    "gulp-jscs": "^3.0.2",
    "gulp-jshint": "^1.11.0",
    "gulp-livereload": "^3.8.0",
    "gulp-load-plugins": "^1.0.0-rc.1",
    "gulp-minify-css": "^1.1.6",
    "gulp-mocha": "^2.1.3",
    "gulp-ng-annotate": "^1.1.0",
    "gulp-ng-constant": "^1.1.0",
    "gulp-node-inspector": "^0.1.0",
    "gulp-plumber": "^1.0.1",
    "gulp-protractor": "^2.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-rev": "^5.0.0",
    "gulp-rev-replace": "^0.4.2",
    "gulp-sass": "^2.0.1",
    "gulp-scss-lint": "^0.2.1",
    "gulp-sort": "^1.1.1",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-svgmin": "^1.1.2",
    "gulp-uglify": "^1.2.0",
    "gulp-useref": "^3.0.3",
    "gulp-util": "^3.0.5",
    "gulp-watch": "^4.3.5",
    "isparta": "^3.5.3",
    "istanbul": "~0.4.1",
    "jasmine-core": "^2.3.4",
    "jasmine-spec-reporter": "^2.4.0",
    "jshint-stylish": "~2.1.0",
    "karma": "~0.13.3",
    "karma-babel-preprocessor": "^5.2.1",
    "karma-chrome-launcher": "~0.2.0",
    "karma-firefox-launcher": "~0.1.6",
    "karma-jade-preprocessor": "0.0.11",
    "karma-jasmine": "~0.3.0",
    "karma-ng-html2js-preprocessor": "~0.2.0",
    "karma-ng-scenario": "~0.1.0",
    "karma-phantomjs-launcher": "~0.2.0",
    "karma-requirejs": "~0.2.2",
    "karma-script-launcher": "~0.1.0",
    "karma-spec-reporter": "~0.0.20",
    "lazypipe": "^0.2.4",
    "mocha": "^2.2.5",
    "nodemon": "^1.3.7",
    "open": "~0.0.4",
    "phantomjs": "^1.9.18",
    "proxyquire": "^1.0.1",
    "requirejs": "~2.1.11",
    "run-sequence": "^1.1.0",
    "sinon": "^1.16.1",
    "sinon-chai": "^2.8.0",
    "supertest": "^1.1.0",
    "utile": "~0.3.0",
    "wiredep": "^2.2.2"
  },

.babelrc

{
  "presets": ["es2015"]
}

Please help I am stuck

**Comment by javimaravillas** [comment]
which code are you using?

**Comment by loganfsmyth** [comment]
You are using `"gulp-babel": "^5.1.0",` which should be `6.x`
