### ISSUE TITLE
JavaScript head out of memory

### ISSUE THREAD

**Issue by JustinDrake** [babel/babelify#226]
I am trying to babelify a pretty large project and it's barfing on me (see below). Any pointers?

> Justins-MacBook-Pro:openbazaar-go-encrypter justin$ browserify index.js -o bundle.js -t babelify --presets es2015
> [BABEL] Note: The code generator has deoptimised the styling of "/Users/justin/tmp/openbazaar-go-encrypter/jsbuild/ob.js" as it exceeds the max of "500KB".
> 
> <--- Last few GCs --->
> 
>    42225 ms: Mark-sweep 1353.6 (1434.8) -> 1349.4 (1434.8) MB, 2178.5 / 0.0 ms [allocation failure] [GC in old space requested].
>    44403 ms: Mark-sweep 1349.4 (1434.8) -> 1349.4 (1434.8) MB, 2177.9 / 0.0 ms [allocation failure] [GC in old space requested].
>    46693 ms: Mark-sweep 1349.4 (1434.8) -> 1352.5 (1407.8) MB, 2289.3 / 0.0 ms [last resort gc].
>    49173 ms: Mark-sweep 1352.5 (1407.8) -> 1355.7 (1407.8) MB, 2479.9 / 0.0 ms [last resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x22a1edbcfb51 <JS Object>
>     2: _serializeMappings(aka SourceMapGenerator_serializeMappings) [/Users/justin/tmp/openbazaar-go-encrypter/node_modules/babel-generator/node_modules/source-map/lib/source-map-generator.js:~291] [pc=0x179c485d44e5] (this=0x15471791b459 <a SourceMapGenerator with map 0x365d8280b479>)
>     3: toJSON(aka SourceMapGenerator_toJSON) [/Users/justin/tmp/openbazaar-go-encrypter/node_modules/babel-gen...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
>  1: node::Abort() [/usr/local/bin/node]
>  2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
>  3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
>  4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
>  5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
>  6: 0x179c478079a7
>  7: 0x179c485d364d
>  8: 0x179c485d44e5
> Abort trap: 6

**Comment by loganfsmyth** [comment]
We recently bumped that limit from 100kb to 500kb and will likely be rolling that back due to issues like this. Until then you should be able to pass `compact: true` to Babel if you don't mind the Babel output not being nice pretty readable code.

**Comment by DrewML** [comment]
@JustinDrake as a test case, what's the size of `ob.js` on disk? Also, can you post your babel configuration?

**Comment by erichonkanen** [comment]
we're getting this same error with an ember project, is there any more information?
```
<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2a48d2825ec1 <JSObject>
    1: number [/Users/eric/Projects/toast/overlord/build/client-web/node_modules/babel-generator/lib/printer.js:~136] [pc=0x2f4e09656feb](this=0x2a48a49f1171 <Generator map = 0x2a48172fb1a9>,str=0x2a489754cdd9 <String[2]: 17>)
    2: NumericLiteral [/Users/eric/Projects/sqwok/overlord/build/client-web/node_modules/babel-generator/lib/generators/types.js:~129] [pc=0x2f4e09911fa5](this=0x2a48a49f1...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by loganfsmyth** [comment]
@erichonkanen Does setting `compact: true` for Babel make the error go away?

**Comment by erichonkanen** [comment]
was confused and got past it, wrong package, thanks!
