### ISSUE TITLE
ParseError: Unexpected token in css

### ISSUE THREAD

**Issue by Stromberg** [babel/babelify#229]
I have an index.js file with:

import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import './index.css';

ReactDOM.render(
  <App />,
  document.getElementById('root')
);

when I run

`
browserify -t [ babelify --presets [ react es2015 ] ] src/index.js -o build/app.js
`

it complains with a parse error in index.css

How can I tell it to not try to parse the css file?

**Comment by loganfsmyth** [comment]
I think you may be misunderstanding. For an import of a CSS file to work, you're going to need a browserify plugin to process the CSS file so it can be bundled into the Browserify JS file. If you don't want it in there, you shouldn't be importing it.
