### ISSUE TITLE
[7.0] babel.util.arrayify and babel.util.canCompile are being removed

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babelify#231]
Currently https://github.com/babel/babel/pull/5487 is proposing the removal of the whole `babel.util` object.

The extensions are now exposed at `babel.DEFAULT_EXTENSIONS`, `canCompile` was very simple, and `extensions` can just be splitting on a comma, so it should be a very easy update for 7.x.

**Comment by shtse8** [comment]
I would lik to know how to upgrade to 7.0 for `arrayify` and `babel.util.list`? Thanks.

**Comment by loganfsmyth** [comment]
@shtse8 If you have a module that needs that behavior, you can certainly implement that logic yourself. It's just that Babel's core APIs have become stricter in what they expect.
