### ISSUE TITLE
Any way to target '.js.jsx'

### ISSUE THREAD

**Issue by hew** [babel/babelify#232]
Is there any way to target .js.jsx?

Neither of these work:

`--extensions .js.jsx`
`--extensions '.js.jsx'`

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

I think you need to use a `,` between extensions?
