### ISSUE TITLE
Backslash in source path on windows

### ISSUE THREAD

**Issue by chesminsky** [babel/babelify#236]
So Chrome thinks it is a file name.
![ziif66fsteq82eub2y9pvw](https://user-images.githubusercontent.com/11498406/27914534-253c2e86-626c-11e7-9dc2-8785eb98d939.png)

**Comment by goto-bus-stop** [comment]
This is most likely a browserify problem. https://github.com/browserify/browserify/pull/1819 may fix it.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
