### ISSUE TITLE
Possible to use babelify for an ES6-written gulpfile.js?

### ISSUE THREAD

**Issue by binarykitchen** [babel/babelify#237]
I do not like to add `babel-core` as another npm dependency in the package.json when we already have babelify. Just do not know/see how we can use babelify to transpile a ES6-written gulpfile.js to ES5 before node.js runs it.

Are there any recipes for that?

**Comment by loganfsmyth** [comment]
I'd generally recommend writing your `gulpfile.js` in node-standard ES6 since Node >= 6 support the vast majority of stuff you'd actually want to use in a Gulpfile.
