### ISSUE TITLE
Does not include all the imports causing the "Cannot find module X" error

### ISSUE THREAD

**Issue by binarykitchen** [babel/babelify#239]
When browserifying with babelify an app of mine using the videomail-client package I get this error

```
Error: Cannot find module './keys' from '/home/michael-heuberger/code/videomail.io/node_modules/videomail-client/dist'
...
```

then I debugged and found out that it's trying to require this one file `_keys` file at this line:
https://github.com/bendrucker/document-visibility/blob/master/index.js#L5

Which makes me wonder why it is not included in the bundle??

For reference, I am importing that document-visibility like that here
https://github.com/binarykitchen/videomail-client/blob/develop/src/wrappers/container.js#L5

Any ideas why that `_keys` file is missing, not bundled within?

**Comment by binarykitchen** [comment]
Just a guess, maybe it is because `module.exports = Visibility` is not at bottom?

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

This doesn't look like something Babel would be affecting.
