### ISSUE TITLE
README does not mention how to include plugins on the command line

### ISSUE THREAD

**Issue by tomjakubowski** [babel/babelify#240]
The README has a few examples of using presets, like:

```
browserify script.js -o bundle.js -t [ babelify --presets [ es2015 react ] ]
```

And there are some mentions of plugins, but it's never spelled out how to use them; I had to find it myself in [index.js](https://github.com/babel/babelify/blob/6d45fa84762f3b57a4b7bef0e1bbdf484614f74d/index.js#L62) (not that that took much time, it's so short!). 

```
browserify script.js -o bundle.js -t [ babelify --presets [ es2015 react ] --plugins [ transform-object-rest-spread ] ]
```

It would be nice to have even one example of using `--plugins` in the README.

**Comment by lostlime** [comment]
+1

**Comment by loganfsmyth** [comment]
Done. https://github.com/babel/babelify/commit/cbd6934ec7a82dc9695f6bf7fc84476129acf025
