### ISSUE TITLE
Can't find variable: Symbol in js

### ISSUE THREAD

**Issue by ramakrishnaj** [babel/babelify#243]
I am getting error "Can't find variable: Symbol"

here

for (var _iterator = this.state.submissionContentSymbol.iterator, _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {

any body can help ?

**Comment by majklovec** [comment]
include babel-polyfill

**Comment by hzoo** [comment]
Yep you need a `Symbol` polyfill which ^ provides. Can combine that with babel-preset-env + `useBuiltIns` option
