### ISSUE TITLE
`debug` option (from babelrc) causes logging to be mixed with script output

### ISSUE THREAD

**Issue by jasonkarns** [babel/babelify#245]
Contrary to unix convention, the `debug` option (via babelrc or transform option in pkg.browserify.transform) causes the debug output to be written to STDOUT. And since browserify operates by writing the compiled code to STDOUT, this results in the debug output being written to the output bundle.

This debugging output should be written to STDERR so that it is properly separated from the JS output itself.

Example:
```
"scripts": {
  "build:umd": "browserify $npm_package_main -s lilsis -d --no-bf | exorcist $npm_package_browser.map > $npm_package_browser"
},
"browserify": {
  "transform": [
    [
      "babelify",
      {
        "presets": [
          [
            "env",
            {
              "debug": true,
              "targets": {
                "browsers": "Last 2 versions, IE 11"
              }
            }
          ]
        ]
      }
    ]
  ]
}
```

<details>
<summary>bundle.js output</summary>
<pre>babel-preset-env: `DEBUG` option

Using targets:
{
  "chrome": "60",
  "android": "4.4.3",
  "edge": "14",
  "firefox": "54",
  "ie": "10",
  "ios": "10",
  "safari": "10"
}

Modules transform: commonjs

Using plugins:
  check-es2015-constants {"android":"4.4.3","ie":"10"}
  transform-es2015-arrow-functions {"android":"4.4.3","ie":"10"}
  transform-es2015-block-scoped-functions {"android":"4.4.3","ie":"10"}
  transform-es2015-block-scoping {"android":"4.4.3","ie":"10"}
  transform-es2015-classes {"android":"4.4.3","ie":"10"}
  transform-es2015-computed-properties {"android":"4.4.3","ie":"10"}
  transform-es2015-destructuring {"android":"4.4.3","edge":"14","ie":"10"}
  transform-es2015-duplicate-keys {"android":"4.4.3","ie":"10"}
  transform-es2015-for-of {"android":"4.4.3","edge":"14","ie":"10"}
  transform-es2015-function-name {"android":"4.4.3","edge":"14","ie":"10"}
  transform-es2015-literals {"android":"4.4.3","ie":"10"}
  transform-es2015-object-super {"android":"4.4.3","ie":"10"}
  transform-es2015-parameters {"android":"4.4.3","ie":"10"}
  transform-es2015-shorthand-properties {"android":"4.4.3","ie":"10"}
  transform-es2015-spread {"android":"4.4.3","ie":"10"}
  transform-es2015-sticky-regex {"android":"4.4.3","ie":"10"}
  transform-es2015-template-literals {"android":"4.4.3","ie":"10"}
  transform-es2015-typeof-symbol {"android":"4.4.3","ie":"10"}
  transform-es2015-unicode-regex {"android":"4.4.3","ie":"10"}
  transform-regenerator {"android":"4.4.3","ie":"10"}
  transform-exponentiation-operator {"android":"4.4.3","ie":"10","ios":"10","safari":"10"}
  transform-async-to-generator {"android":"4.4.3","edge":"14","ie":"10","ios":"10","safari":"10"}
  syntax-trailing-function-commas {"android":"4.4.3","ie":"10"}
(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.lilsis = f()}})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
...
</pre></details>

Notice the debug lines are in the same file as the bundled JS.

The debug output ought to be printed to STDERR.

**Comment by loganfsmyth** [comment]
Closing in favor of https://github.com/babel/babel/issues/6597
