### ISSUE TITLE
Code duplication for babel polyfills when using babelify

### ISSUE THREAD

**Issue by essenmitsosse** [babel/babelify#246]
When I use babelify via browserify it seems to be converting each module on its own. This means, each module gets all the polyfills it needs. This leads to massive code bloat.

On the other hand, when I run babel on the the output of browserify (without babelify), all polyfills get moved to the top and only appear once.

Is this intended behaviour? Am I expecting something here that is not intended to work like that?

# Example

The code is non-sensical, but it shows the issue.

## Input
```javascript
/* main.js */
const foo = require( './foo.js' );
console.log( ...foo( [ 1, 2 ] ) );
```
```javascript
/* foo.js */
function getFoo( args ) { return args; }

function foo( args ) {
        return [ ...getFoo( args ) ];
}

module.exports = foo;
```
## Browserify with Babelify
Note that `_toConsumableArray` is defined twice. It would be redefined for each additional module that would need it.

```javascript
(
/* I omitted the Browserify shims for readability */
)( { 1: [ function ( require, module, exports ) {
        
/* #1 */function _toConsumableArray(arr) { /* function omitted for readiability */ }

        function getFoo(args) { return args; }
        function foo(args) { return [].concat(_toConsumableArray(getFoo(args))); }
        module.exports = foo;
        
}, {} ],
2: [ function ( require, module, exports ) {
        
        var _console;
        
/* #2 */function _toConsumableArray(arr) { /* function omitted for readiability */ }
        
        var foo = require( './foo.js' );
        ( _console = console ).log.apply( _console, _toConsumableArray( foo( [ 1, 2 ] ) ) );
        
}, { './foo.js': 1 } ] }, {}, [ 2 ] );

```

## Browersify without Babelify, then babel on the resulting file.

Note, that `_toConsumableArray` is put above everything else and only defined once.

```javascript
"use strict";

/// First and only definition.
function _toConsumableArray(arr) { /* function omitted for readiability */ }

(
/* I omitted the Browserify shims for readability */
)( { 1: [ function ( require, module, exports ) {
        
        function getFoo(args) { return args; }
        function foo(args) { return [].concat(_toConsumableArray(getFoo(args))); }
        module.exports = foo;
        
}, {} ],
2: [ function ( require, module, exports ) {
        
        var _console;
        var foo = require( './foo.js' );
        ( _console = console ).log.apply( _console, _toConsumableArray( foo( [ 1, 2 ] ) ) );
        
}, { './foo.js': 1 } ] }, {}, [ 2 ] );
```

**Comment by goto-bus-stop** [comment]
This is expected behaviour, yes. [babel-plugin-transform-runtime](https://npmjs.com/package/babel-plugin-transform-runtime) can be used to add helpers only once.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
