### ISSUE TITLE
Changelist?

### ISSUE THREAD

**Issue by gesa** [babel/babelify#249]
v8.0.0 was just released, but it's unclear what the breaking changes may have been. I couldn't seem to find a changelist either.

**Comment by hzoo** [comment]
Ah ya sorry, totally forgot 😋, I'll add it to the github releases but in short it just drops node 0.10/0.12 + peerDep on babel-core in preparation for Babel 7 (did the same thing for grunt/gulp/webpack pkgs)

Thanks for the reminder

**Comment by gesa** [comment]
great, thank you so much!

**Comment by hzoo** [comment]
Done https://github.com/babel/babelify/releases/tag/v8.0.0
