### ISSUE TITLE
Using babelify with new scoped packages

### ISSUE THREAD

**Issue by larsgw** [babel/babelify#251]
Today I installed the new scoped packages of babel, e.g. `@babel/core` etc., including the plugins, e.g. `@babel/plugin-proposal-pipeline-operator` etc. However, `babelify@8` still requires the 'old' `babel-core` package, AFAICT. I first installed `babel-core@6` by accident, which had problems with the new `.babelrc` plugin syntax (before it would prefix `babel-plugin-` to get the package, I think; now it'd need to add `plugin-` between `@babel/` and the plugin name).

However, `babel-core@7.0.0-beta.3`, the latest I could find, gave the following error instead:

```
/home/larsw/project_dir/node_modules/babelify/index.js:65
  if (!babel.util.canCompile(filename, extensions)) {
                  ^

TypeError: Cannot read property 'canCompile' of undefined
  at /home/larsw/project_dir/node_modules/babelify/index.js:65:21
  at Babelify (/home/larsw/project_dir/node_modules/babelify/index.js:10:36)
  at nr (/home/larsw/project_dir/node_modules/module-deps/index.js:301:23)
  at onfile (/home/larsw/project_dir/node_modules/resolve/lib/async.js:56:21)
  at onex (/home/larsw/project_dir/node_modules/resolve/lib/async.js:104:32)
  at /home/larsw/project_dir/node_modules/resolve/lib/async.js:24:24
  at FSReqWrap.oncomplete (fs.js:153:5)
```

Note: I'm not sure if it's possible to use babelify with the new scoped packages at all.

**Comment by larsgw** [comment]
Here's my `.babelrc`:

```js
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "browser": [
          "> 1%",
          "last 10 versions",
          "ie > 7"
        ]
      }
    }]
  ],
  "plugins": [
    "@babel/proposal-unicode-property-regex"
  ],
  "env": {
    "test": {
      "plugins": ["istanbul"]
    }
  }
}
```

**Comment by noygal** [comment]
Getting the same error after changing the `babel-core' to point to the new scoped packages:

```
  "dependencies": {
    "@babel/cli": "^7.0.0-beta.32",
    "@babel/core": "^7.0.0-beta.3",
    "@babel/preset-env": "^7.0.0-beta.32",
    "@babel/preset-react": "^7.0.0-beta.32",
    "@babel/preset-stage-0": "^7.0.0-beta.32",
    "babel-core": "@babel/cli",
    "babelify": "^8.0.0"
  }
```

**Comment by larsgw** [comment]
I didn't even know you could do that. Does it work if you point it to `@babel/core` instead of `@babel/cli`, or was that just a typo? I can't test right now.

**Comment by noygal** [comment]
Nope my bad, can't do that with npm...

But I did investigate some farther, the issue is with this condition:
https://github.com/babel/babelify/blob/master/index.js#L65

Babel 7 remove the util object all together: https://github.com/babel/babelify/issues/231

I wanted to try my initial approach (replacing the `babel-core` with `@babel/core`), so I comment out those [lines](https://github.com/babel/babelify/blob/master/index.js#L65-L67) in the code and manually copied the `@babel/core` folder to `babel-core`:

```
rm -rf node_modules/babel-core
cp -a node_modules/\@babel/core/. node_modules/babel-core
```

I'm glade to say that this hack works!

**Comment by noygal** [comment]
I've open PR for this issue: https://github.com/babel/babelify/pull/252

Meanwhile you can replace the package with my package:
```json
"dependencies": {
    "@babel/core": "^7.0.0-beta.3",
    "@babel/preset-env": "^7.0.0-beta.32",
    "babel-core": "^6.26.0",
    "babelify": "git+https://github.com/noygal/babelify.git#feature/babel-7-support",
  }
```
And use the new options `babel` to pass your own babel package:
```js
browserify().transform('babelify', {
  presets: ['@babel/preset-env'],
  babel: require('@babel/core')
})
```

**Comment by niftylettuce** [comment]
bump
