### ISSUE TITLE
Node module script not recognised as ES6 module

### ISSUE THREAD

**Issue by jono-hayward** [babel/babelify#253]
So I'm getting the dreaded `'import' and 'export' may only appear with 'sourceType: Module'` error when running browserify. But I'm pretty sure I'm already applying the transform correctly with the right presets.

For context: Running the latest versions of browserify and babelify in a gulp build process. I've got the `babel-preset-env` preset installed. Based on [this FAQ](https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed), in my package.json I'm configuring browserify thus:
``` JSON
"browserify": {
    "transform": [
      "browserify-shim",
      [ "babelify", { "presets": [ "env" ] } ]
    ]
  }
```
Removing `browserify-shim` doesn't affect this issue.

I've also tried the other approach, using it as a global transform on the `browserify()` call inside my gulpfile but that hasn't helped either. 

So I'm forced to guess that the problem may be with the [module I'm including](https://github.com/slventures/googlemaps-js-rich-marker/blob/gh-pages/src/richmarker.es6), but I'm not confident about that. Is there anything about that file that looks like it may cause babelify to not recognise it as a valid ES6 module?

**Comment by loganfsmyth** [comment]
If you need to run Babel on files in `node_modules`, the important flag is `global: true` from the FAQ page. In generally I'd recommend not recommend using `node_modules` dependencies that include `import` or `export` though.
