### ISSUE TITLE
Relative paths not updated

### ISSUE THREAD

**Issue by btilford** [babel/babelify#261]
Not sure if this is a bug or I'm configuring something wrong. Pretty much exhausted the documentation and google though.

I've created an [example project](https://github.com/btilford/browserify-amd-issue) that demonstrates the issue.

My scenario is we have a large number of projects that are built with [grunt-contrib-requirejs](https://github.com/gruntjs/grunt-contrib-requirejs) right now we don't have the resources to move _everything_ away from grunt/r.js compilation. Using a grunt/browserify on a couple of new projects I've ran into issues consuming them in downstream projects that use grunt/r.js due to relative paths. Using aliases I _think_ been able to update the exported module names however all the imports/requires that reference them remain relative which breaks anything that tries to use them through requirejs.

I've tried the different config options like `standalone` which will get past compilation and fail at runtime but nothing has worked so far. If there were an option to output each module into it's own umdified file that might even be better since unused modules wouldn't be compiled into the downstream project.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
