### ISSUE TITLE
npm install babelify@next: No compatible version found: babelify@next

### ISSUE THREAD

**Issue by Mingun** [babel/babelify#263]
[Installation](https://github.com/babel/babelify#installation) section of readme recommends install babelify as
```console
# Babel 7
$ npm install --save-dev babelify@next @babel/core
```
But when I try follow this recommendations I get error:
```
>npm install --save-dev babelify@next
npm ERR! Windows_NT 6.0.6001
npm ERR! argv "D:\\Scripts\\JavaScript\\node.exe" "D:\\Scripts\\JavaScript\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "babelify@next"
npm ERR! node v5.12.0
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: babelify@next
npm ERR! notarget Valid install targets:
npm ERR! notarget 8.0.0, 7.3.0, 7.2.0, 7.1.0, 7.0.2, 7.0.1, 7.0.0, 6.4.0, 6.3.0, 6.2.0, 6.1.3, 6.1.2, 6.1.1, 6.1.0, 6.0.2, 6.0.1, 6.0.0, 5.0.5, 5.0.4, 5.0.3, 5.0.2, 5.0.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\other\structured-diff\npm-debug.log
```
Where I'm wrong?

**Comment by batje** [comment]
same here, on ubuntu, with node 8.x

**Comment by goto-bus-stop** [comment]
that's correct, master is not published yet.

**Comment by batje** [comment]
figured that https://www.npmjs.com/package/babelify

**Comment by huaSolna** [comment]
+1

**Comment by VitaliyR** [comment]
+1

**Comment by optimum7com** [comment]
+1

**Comment by Blinnikov** [comment]
As I see babel/babel#7764 has already been merged. Any progress on it in babelify repository?

**Comment by goto-bus-stop** [comment]
That PR is merged but not yet in a release. I opened a PR on this repository (mobile, sorry for no link) that works with babel/babel#7764 so that can go in after the next Babel release. Then babelify@next is probably good to go

On 7 May 2018 16:46:12 CEST, Igor Blinnikov <notifications@github.com> wrote:
>As I see babel/babel#7764 has already been merged. Any progress on it
>in babelify repository?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/babel/babelify/issues/263#issuecomment-387088407

-- 
Sent from mobile. Please excuse my brevity.

**Comment by ruzpuz** [comment]
@goto-bus-stop Not sure if related but at this moment I am trying to make babelify work with babel 7. And well https://github.com/babel/babelify the instructions here say to install next version - that fails. 

Latest version (8.0.0) tries to access the old babel-core. Any way to solve this?

**Comment by goto-bus-stop** [comment]
It'll work once the `@next` version is released.

**Comment by ruzpuz** [comment]
@goto-bus-stop point taken. might I ask whether that would happen soon?  If that will not happen soon - we will have to find some workaround, but I would prefer to know :)

**Comment by goto-bus-stop** [comment]
Soon after the next Babel beta. I don't know when that will be :woman_shrugging:

**Comment by michaelthuren** [comment]
Hi guys, any news on the release? :-)

**Comment by goto-bus-stop** [comment]
@zertosh I think babelify is ready for a v9 npm release tag. Would you have some time to do an `npm publish --dist-tag=next` or to add the babelify package to the `babel` npm org?

**Comment by zertosh** [comment]
@goto-bus-stop, latest is at v8.0.0 and next is at v9.0.0 now
