### ISSUE TITLE
Ignore option throwing errors

### ISSUE THREAD

**Issue by larsgw** [babel/babelify#265]
Using the `ignore` option results in the following error:

```
TypeError: Cannot read property 'code' of null while parsing file: /home/larsw/project/node_modules/expect.js/index.js
    at babel.transform (/home/larsw/project/node_modules/babelify/index.js:31:25)
    at /home/larsw/project/node_modules/@babel/core/lib/transform.js:29:32
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Using the following babelify options:

```js
{
  global: true,
  ignore: ['node_modules/expect.js/']
}
```

## Source (AFAICT)

Caused by this, due to `result` being null:

https://github.com/babel/babelify/blob/c5e4d40b99d18dc99091815890713e2dfd614608/index.js#L31

This happens on ignored files, as expected. My guess is that that happens because of

```js
    if (
      ignoreFile &&
      shouldIgnore(context, ignoreFile.ignore, null, ignoreFile.dirname)
    ) {
      return null;
    }
```
in [`@babel/core`](https://github.com/babel/babel/blob/55ef39eb87a09eeafee6d89d70443c6ef6cbef64/packages/babel-core/src/config/config-chain.js#L175-L180).

This causes

* `loadPrivatePartialConfig` to return `null`
  ```js
  const configChain = buildRootChain(args, context);
  if (!configChain) return null;
  ```
  ([source](https://github.com/babel/babel/blob/55ef39eb87a09eeafee6d89d70443c6ef6cbef64/packages/babel-core/src/config/partial.js#L40-L41)), which causes
* `loadFullConfig` to return `null`
  ```js
  const result = loadPrivatePartialConfig(inputOpts);
  if (!result) {
    return null;
  }
  ```
  ([source](https://github.com/babel/babel/blob/55ef39eb87a09eeafee6d89d70443c6ef6cbef64/packages/babel-core/src/config/full.js#L49-L52)), which causes
* `loadConfig` to return `null`
  ```js
  const config = loadFullConfig(opts);

  return config ? config.options : null;
  ```
  ([source](https://github.com/babel/babel/blob/55ef39eb87a09eeafee6d89d70443c6ef6cbef64/packages/babel-core/src/config/index.js#L16-L18)), which causes
* `transform` to return `null`
  ```js
  cfg = loadConfig(opts);
  if (cfg === null) return cb(null, null);
  ```
  ([source](https://github.com/babel/babel/blob/55ef39eb87a09eeafee6d89d70443c6ef6cbef64/packages/babel-core/src/transform.js#L38-L39))

---

Program|Version
---|---
Babel|v7.0.0-beta.44
Babelify|v8.0.0 (plus the #255 PR)
Browserify|v16.2.0
Node.js|v8.11.2

Full options:

```js
browserify()
  .exclude(['citation-js'])
  .add('./test/wrapper.js')
  .transform(babelify, {
    global: true,
    ignore: ['node_modules/expect.js/']
  })
  .bundle()
  .pipe(fs.createWriteStream(path.join(__dirname, '../build/test.citation.js')))
```

**Comment by loganfsmyth** [comment]
Fixed in https://github.com/babel/babelify/pull/267
