### ISSUE TITLE
Don't want to process `node_modules` files

### ISSUE THREAD

**Issue by imfaisalkh** [babel/babelify#271]
I'm using `babelify` in my gulp task like this.

```
 gulp.task( 'compileJS', function() {
    browserify( './scripts/es/main.js')
    .transform( babelify ) // Transpiles all ES6 JS to ES5 JS code.
    .bundle()
    .pipe( source( 'bundle.js' ) )
    .pipe( gulp.dest( './scripts/js/') )
 })
```

Now in my `main.js` file i'm importing many modules from `node_modules`. The issue is that this task not only imports the node module's file (i.e. the `main` file defined in respective module's `package.json` file) but it also imports any dependecies of that file too.

What I want is to simply import the module file "as it is" without processing it. How can I achieve this behaviour?

**Comment by loganfsmyth** [comment]
Could you clarify your overall goal? The entire goal of Browserify is to bundle up an entire application, including dependencies. If the objective is to compile only a single file, you'd likely want to use something like `gulp-babel` instead.

I'm not sure I understand what you mean by

> import the module file "as it is" without processing it

**Comment by imfaisalkh** [comment]
There are many import statements in my main.js file (application code). Some imports are for my application code (files loacated in /scripts/es/ folder) but other imports are for node_modules libraries. I want to bundle up both type of imports, but when babelify import any node module's file (normally from dist folder of that module) it also looks for any other require statement in this file, if there is any, it imports that dependency of the node module too (even if it is a dist file). I dont want it to entertain any require statement within any node module file.

**Comment by imfaisalkh** [comment]
One example is `magnific-popup` node library. If import this library in my application code like this `import 'magnific-popup'` it imports `node_modules/magnific-popup/dist/jquery.magnific-popup.js` file (which is exactly I need). Now, this file contains some code like this:

```
if (typeof define === 'function' && define.amd) { 
 // AMD. Register as an anonymous module. 
 define(['jquery'], factory); 
 } else if (typeof exports === 'object') { 
 // Node/CommonJS 
 factory(require('jquery')); 
 } else { 
 // Browser globals 
 factory(window.jQuery || window.Zepto); 
 } 
 }
```

Due  to this code it is also importing the `jquery` library together with `jquery.magnific-popup.js` file content. I don't want `jquery` code because this library is already available at run-time for my app.

**Comment by loganfsmyth** [comment]
None of this seems related to Browserify, these are general questions about how Browserify handles subdependencies. For instance

> I don't want jquery code because this library is already available at run-time for my app.

you could use something like 
 https://stackoverflow.com/questions/22987220/browserify-using-jquery-globally-and-in-module to use a global version of jQuery.
