### ISSUE TITLE
The global option is not available in babel 7.0.0 ?

### ISSUE THREAD

**Issue by l00mi** [babel/babelify#272]
According to https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed we can use `global:true` to compile all node_modules. This seems not be an option anymore in babel 7.0.0. Is this correct? If yes is there another way to transform all node_modules?

**Comment by goto-bus-stop** [comment]
The `global: true` option is a browserify option, not a babelify one. You can only use the `global: true` option in the browserify CLI and API, not in package.json.

```bash
browserify -g babelify
# -g instead of -t
```
```js
browserify(...).transform('babelify', { global: true, ... })
```

**Comment by l00mi** [comment]
Got it, I was taking the wrong turn somewhere in this inception game (-:

Thank you.
