### ISSUE TITLE
Boolean options fail (e.g. --compact true)

### ISSUE THREAD

**Issue by mtmacdonald** [babel/babelify#281]
This command works:

`babelify --compact auto --presets [ @babel/preset-env @babel/preset-react ]`

But if I change `--compact auto` to `--compact true`, I get an error:

`Error: .compact must be a boolean, "auto", or undefined while parsing file`

It seems like boolean options are registered as strings and not boolean types. The failure seems to happen with Babelify 10 but not Babelify 8.

**Comment by goto-bus-stop** [comment]
I think you may need to do `babelify --compact --presets` to set `compact: true`. And `--no-compact` to set `compact: false`.
