### ISSUE TITLE
TypeError: Cannot read property 'arrayify' of undefined

### ISSUE THREAD

**Issue by geanfrancovolpe** [babel/babelify#288]
I'm using gsap in my typescript project, and compiling it with gulp + browserify + babelify and throws me this error: TypeError: Cannot read property 'arrayify' of undefined. 

these are my dependencies:
    "@babel/cli": "^7.5.5",
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "babel-core": "^7.0.0-bridge.0",
    "babel-preset-es2015": "^6.24.1",
    "babelify": "^8.0.0"

I've been looking for a solution, and found that arrayify, canCompile utils functions were removed from new babel version, maybe the "babelify" dependency is not updated to not work with these functions?

**Comment by goto-bus-stop** [comment]
You're using a version of babelify that only works with Babel 6. the latest version, babelify@10, works with babel 7.

You've also got a babel-preset-es2015 in your package.json, which only works with Babel 6; if you are using Babel 7, it should be removed. @babel/preset-env does everything preset-es2015 does and more.

**Comment by geanfrancovolpe** [comment]
thanks dude you're right, i was configuring the gulp file from the typescript gulp tutorial and is outdated.
