### ISSUE TITLE
Is this incompatible with Babel 7?

### ISSUE THREAD

**Issue by blaasvaer** [babel/babelify#291]
It just started throwing all sorts of errors ...

**Comment by goto-bus-stop** [comment]
babelify v10 is _only_ compatible with babel 7. could you list the babelify, babel, and plugin versions that you're using, and share the errors you're getting?

**Comment by blaasvaer** [comment]
Well, as always ... after messing around (for ages) with updating random dependencies, node versions and what not I managed to make it work – again ... but this whole npm dependencies hell crap is coming off as an incredibly rocky road for development. Out of the blue, you get kicked over the shin if you dare to touch only one single part of your build process.

**Comment by blaasvaer** [comment]
The world has gone crazy ... and especially the front end world has gone totally crazy ; )
