### ISSUE TITLE
CPU intensive hanging

### ISSUE THREAD

**Issue by gaving** [babel/babelify#47]
I'm having a bit of an issue using babelify with a watchify gulp task. Gist here: https://gist.github.com/gaving/c1dce867b8e4fa86e5c9

Versions:-

    "babelify": "^5.0.3",
    "browserify": "^9.0.2",
    "watchify": "^2.4.0",

Gulp just hangs entirely and the CPU pegs at 100% until I have to SIGINT.

Are their any known issues with later browserify versions? Not sure if https://github.com/babel/babelify/issues/27 is related.

**Comment by sebmck** [comment]
Try running:

```sh
$ DEBUG=babel gulp watchify`
```

It'll give a debug output of the current file being parsed so you can narrow down if it's babel causing the issue or if there's a specific file that's the problem or if your dependencies are also being transformed inadvertently etc.

**Comment by gaving** [comment]
Ah, nice! Spent ages hunting to try and find some sort of debug command like that too :)

So it turns out it isn't babel at all and I just wasn't being patient enough.

    [......]
    babel /Users/gavin/Sandbox/test/bower_components/jquery/dist/jquery.js: Running transformer _aliasFunctions +42ms
    babel /Users/gavin/Sandbox/test/bower_components/jquery/dist/jquery.js: Running transformer _moduleFormatter +96ms
    babel /Users/gavin/Sandbox/test/bower_components/jquery/dist/jquery.js: Running transformer es3.propertyLiterals +45ms
    babel /Users/gavin/Sandbox/test/bower_components/jquery/dist/jquery.js: Running transformer es3.memberExpressionLiterals +49ms
    babel /Users/gavin/Sandbox/test/bower_components/jquery/dist/jquery.js: Running transformer _cleanUp +48ms
    babel /Users/gavin/Sandbox/test/bower_components/jquery/dist/jquery.js: Running transformer _declarations +47ms
    [14:35:11] Finished 'watchify' after 1.38 min

Cheers for the quick response.

**Comment by sebmck** [comment]
Ah, you should probably make babelify ignore `bower_components` as it'll be running unnecessarily transforming the files included. Replacing:

```javascript
bundler.transform(babelify);
```

with

```javascript
bundler.transform(babelify.configure({
  ignore: "bower_components"
}));
```

should do the trick and your compilation time will be **signifcantly** reduced.

**Comment by gaving** [comment]
Awesome. Changed the line and:-

    [14:47:21] Finished 'watchify' after 3.68 s

Thanks again man, appreciate it. :beers:
