### ISSUE TITLE
Browserify with Babelify fails on JSX

### ISSUE THREAD

**Issue by ivan-kleshnin** [babel/babelify#55]
I'm interested in this project and foremost in CLI usage. It makes possible for me to remove "middleman" `build` folder where I keep ES5 files and handle them further with browserify. 
Cut one build step – isn't that exciting?!

But I just can't run this with browserify.
I've tried several command variations and all of them fail on React JSX syntax.
```
$ browserify -d -e frontend/app/app.js -t [ babelify --experimental --sourceMapRelative . ]
$ browserify -d -e frontend/app/app.js -t babelify
$ browserify frontend/app/app.js -t babelify
...

Error: Parsing file /Users/xxx/demo/node_modules/frontend/robot/components/index.js: Unexpected token (21:6) 
```

(21:6) position is the beginning of JSX syntax.
   
**This happens if file with JSX syntax is not TOP-level**

Documentation of Browserify (https://github.com/substack/node-browserify) separates 
`-t` and `-g` transformations, though their descriptions are not clear to me.
When I replace `-t` with `-g`, everything fails with different error:

```
$ browserify -d -e frontend/app/app.js -g [ babelify --experimental --sourceMapRelative . ]
$ browserify -d -e frontend/app/app.js -g babelify
$ browserify frontend/app/app.js -g babelify
...

ReferenceError: Unknown option: global while parsing file: /Users/xxx/demo/frontend/app/app.js
```

I don't know how to define those transformations in correct way. Please document.

**Comment by sebmck** [comment]
Is your code within a folder called `node_modules`? The following from the [docs](https://github.com/babel/babelify#cli) **does** work:

```sh
$ browserify script.js -t babelify --outfile bundle.js
```

**Comment by ivan-kleshnin** [comment]
> Is your code within a folder called node_modules?

I use symlinks to avoid relative imports. May they be the problem?
./node_modules/frontend -> ./frontend/app
./node_modules/backend -> ./backend/app
./node_modules/shared -> ./shared

**Comment by sebmck** [comment]
@ivan-kleshnin Most likely. Browserify will ignore `node_modules`. You could try my suggestion [here](https://github.com/babel/babelify/issues/53#issuecomment-76497982) about adding a `package.json` to each of your folders in `node_modules` with:

```json
{
  "browserify": {
    "transform": ["babelify"]
  }
}
```

**Comment by ivan-kleshnin** [comment]
Your suggestion helped. Thank you! Now I have only a problem with experimental flag.
None of the following works:

```
{
  "browserify": {
    "transform": ["babelify --experimental"]
  }
}

{
  "browserify": {
    "transform": ["[babelify --experimental]"]
  }
}

{
  "browserify": {
    "transform": ["babelify", "--experimental"]
  }
}
```

**Comment by sebmck** [comment]
```javascript
{
  "browserify": {
    "transform": [["babelify", { "experimental": true }]]
  }
}
```

**Comment by ivan-kleshnin** [comment]
Yep, thats :v:
