### ISSUE TITLE
Issue with browserify-shim 

### ISSUE THREAD

**Issue by reggi** [babel/babelify#56]
I seem to be running in circles with this.

The original issue is in [thlorenz/browserify-shim#145](https://github.com/thlorenz/browserify-shim/issues/145#issuecomment-76622192)

If I run ` -t [browserify-shim]` and use normal CommonJS syntax `require()` then the browserify bundle works perfectly. 

If I run `-t [babelify --only \"./index.js\" browserify-shim] and use es6  `import` syntax I get an error within my imported shimmed dependency (polymer).

There's a simple demo here:

https://github.com/reggi/demo-browserify-polymer-es6

Why would it compile perfectly without `babelify` and when I specify `--only` it have a different effect on my included shimmed dependency?

**Comment by sebmck** [comment]
I can't even `bower install`:

```
$ bower install
bower polymer#~0.5.5            cached git://github.com/Polymer/polymer.git#0.5.5
bower polymer#~0.5.5          validate 0.5.5 against git://github.com/Polymer/polymer.git#~0.5.5
bower core-component-page#^0.5  cached git://github.com/Polymer/core-component-page.git#0.5.5
bower core-component-page#^0.5         validate 0.5.5 against git://github.com/Polymer/core-component-page.git#^0.5
bower webcomponentsjs#^0.5               cached git://github.com/Polymer/webcomponentsjs.git#0.5.5
bower webcomponentsjs#^0.5             validate 0.5.5 against git://github.com/Polymer/webcomponentsjs.git#^0.5
bower                                     error Maximum call stack size exceeded

Stack trace:
RangeError: Maximum call stack size exceeded
    at Array.sort (native)
    at Manager.toData (/Users/sebastian/node_modules/bower/lib/core/Manager.js:222:55)
    at Manager.<anonymous> (/Users/sebastian/node_modules/bower/lib/core/Manager.js:224:44)
    at Array.forEach (native)
    at Manager.toData (/Users/sebastian/node_modules/bower/lib/core/Manager.js:223:15)
    at Manager.<anonymous> (/Users/sebastian/node_modules/bower/lib/core/Manager.js:224:44)
    at Array.forEach (native)
    at Manager.toData (/Users/sebastian/node_modules/bower/lib/core/Manager.js:223:15)
    at Manager.<anonymous> (/Users/sebastian/node_modules/bower/lib/core/Manager.js:224:44)
    at Array.forEach (native)

Console trace:
Trace
    at StandardRenderer.error (/Users/sebastian/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.<anonymous> (/Users/sebastian/node_modules/bower/bin/bower:109:18)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:166:7)
    at Logger.emit (/Users/sebastian/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/sebastian/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/Users/sebastian/node_modules/bower/node_modules/q/q.js:808:24)
    at /Users/sebastian/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/Users/sebastian/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/Users/sebastian/node_modules/bower/node_modules/q/q.js:752:41)

System info:
Bower version: 1.2.8
Node version: 1.4.1
OS: Darwin 14.1.0 x6
```

**Comment by sebmck** [comment]
> If I run `-t [babelify --only \"./index.js\" browserify-shim]` and use es6import syntax I get an error within my imported shimmed dependency (polymer).

Because the `--only` argument will **only** run `babelify` on `index.js`. Checking out that repo and running:

```sh
$ npm run babel-before
```

Works without a problem.

**Comment by reggi** [comment]
Hey @sebmck thanks for the response! I'm getting an error. The only way I can get it to run is without using babelify. The only reason it works is because I'm not using es6 imports in that demp :crying_cat_face: 

![screen shot 2015-03-01 at 8 36 34 pm 1](https://cloud.githubusercontent.com/assets/296798/6434267/b4a1c5f4-c052-11e4-8578-178bf9de4d86.png)

```
 function element(name, prototype) {
    if (typeof name !== 'string') {
      var script = prototype || document._currentScript;
      prototype = name;
      name = script && script.parentNode && script.parentNode.getAttribute ?
          script.parentNode.getAttribute('name') : '';
      if (!name) {
        throw 'Element name could not be inferred.';
      }
    }
    if (getRegisteredPrototype(name)) {
      throw 'Already registered (Polymer) prototype for element ' + name;
    }
    // cache the prototype
    registerPrototype(name, prototype);
    // notify the registrar waiting for 'name', if any
    notifyPrototype(name);
  }
bundle-babel-before.js:3 Uncaught TypeError: Cannot set property 'esprima' of undefined
bundle-babel-after.js:6387 Uncaught HierarchyRequestError: Failed to execute 'appendChild' on 'Node': Nodes of type 'HTML' may not be inserted inside nodes of type '#document'.
bundle-without-babel.js:10400 Uncaught TypeError: Cannot read property 'resolveDom' of undefined
```

**Comment by reggi** [comment]
@sebmck It's just apparent that it's a babilfy issue then because it works without babelify.  That's why I wen't with `--only` to stop babelify from processing `polymer`.

**Comment by sebmck** [comment]
@reggi You should be ignoring `bower_components` anyway with:

```sh
$ browserify -t [babelify --ignore \"bower_components\" browserify-shim]
```

Since otherwise `bower_components` will be unnecessarily transformed.

**Comment by zertosh** [comment]
@reggi I took a quick look at your repo and `es6-polymer-babel-index-shimmed.js` works with:

```sh
# backslashes for readability only
node ./node_modules/.bin/browserify ./index-es6.js \
  -t [ babelify --ignore bower_components ] \
  -t browserify-shim \
  --debug \
  > es6-polymer-babel-index-shimmed.js
```

You need to ignore `bower_components` because since it's not `node_modules`, browserify will apply the babelify transform to it. Also, transforms need to specified separately.

If you're curious about why polymer didn't like to get babeled, it's because it doesn't seem to work in [strict mode](http://babeljs.io/docs/advanced/transformers/other/strict/). If you turn off that babel transform, it also works:

```sh
node ./node_modules/.bin/browserify ./index-es6.js \
  -t [ babelify --blacklist strict ] \
  -t browserify-shim \
  --debug \
  > es6-polymer-babel-index-shimmed.js
```

Though, it's more efficient to simply ignore `bower_components` since you don't want it transformed at all.

PS: There is no `--test` flag. You probably meant `--debug` for source maps.

**Comment by zertosh** [comment]
This seems resolved to me.
