### ISSUE TITLE
Use options from babelrc in cwd

### ISSUE THREAD

**Issue by bvalosek** [babel/babelify#58]
Would it possible to have the `.babelrc` file checked when running the browserify transform? This would allow compiler settings to live in a separate file vs. living in package.json or build scripts.

**Comment by sebmck** [comment]
I've been holding off on adding this functionality to the plugins because if it's going to be added to one then it's going to be added to all of them and `.babelrc` is currently undocumented.

**Comment by gaearon** [comment]
It is now, isn't it?

**Comment by sebmck** [comment]
Oh yeah, it is as of Babel 5.0.0 and Babelify 6.x. Thanks @gaearon!

**Comment by askmatey** [comment]
> `babelrc` 	`null` 	Specify a custom file path to load a .babelrc config from.
See http://babeljs.io/docs/usage/options/

Example:
```js
babelify.configure({
  babelrc: './.babelrc'
}
```

https://babeljs.io/docs/usage/babelrc/

**Comment by sebmck** [comment]
@askmatey You shouldn't have to specify any config.

**Comment by askmatey** [comment]
@sebmck Yes I know :+1: , but the option is useful for different build targets

**Comment by nathanmarks** [comment]
@sebmck @askmatey Agreed, can it just look for .babelrc by default?

**Comment by sebmck** [comment]
@nathanmarks It does.

**Comment by nathanmarks** [comment]
@sebmck Awesome, disregard what I said. Totally misunderstood the exchange above... stumbled on here while googling to check if babelify supported the .babelrc file.
