### ISSUE TITLE
Unable to set ignore: false

### ISSUE THREAD

**Issue by cw-peter** [babel/babelify#59]
This line: https://github.com/babel/babelify/blob/master/index.js#L14
 means that it is impossible to pass `ignore: false`, as is mentioned in the docs here: https://babeljs.io/docs/usage/require/

**Comment by sebmck** [comment]
Those are the docs for `babel/require` not `babelify`. If you're trying to make Babel parse `node_modules` then it's completely unrelated as `babelify` doesn't ignore any files by default. Please see #53, #44 and #38 for possible workarounds if this is the case.

**Comment by cw-peter** [comment]
Oh wow, you were quick. Thanks!

**Comment by sebmck** [comment]
No problem! Check out our [gitter room](https://gitter.im/babel/babel) if you have anymore questions.

**Comment by cw-peter** [comment]
will do, thanks for an awesome module :)
