### ISSUE TITLE
Update teh version of babelify in npm

### ISSUE THREAD

**Issue by kileras** [babel/babelify#60]
It would be cool if we can have an updated version of babelify in npm so we can have some of the fixes since 5.0.3.

**Comment by sebmck** [comment]
Please see #51 and #42.

**Comment by kileras** [comment]
Hi,

I'm a bit lost, the thing is that I made a pull request to fix the global arguments last week (https://github.com/babel/babelify/pull/50) and I think if I'm not mistaken that the current version, 5.0.3, doesn't have that changes since I just did a npm install and I still see the issue.

Is just because right now I'm using babelify by pointing to my fork but my npm proxy have some issues with that and I don't want to publish the fork in npm if I don't need too :D

Cheers!

**Comment by sebmck** [comment]
Oh wait sorry, got confused and thought you wanted the version of `babel-core` bumped. Could've sworn I pushed out a new version, I'll do it now if I haven't.

**Comment by kileras** [comment]
Perfect, thank you! 

Also I just realise that there is a question in the faqs about babelify not transpiling node_modules, well that fix is for that so you can actually do it:

{
  "browserify": {
    "transform": [["babelify", {"global": true }]]
  }
}

That will tell browserify to transform everything, which is what I'm currently doing 😄

Cheers!
