### ISSUE TITLE
how's it happens? while compiling?

### ISSUE THREAD

**Issue by benji0818** [babel/babelify#61]
If I add "babelify" transform into package.json, an unexpected error occured.

code:
```javascript
var a = {
  b: function() {
    // do nothing
  }
};
```

result:
```javascript
var a = {
  b: function b() {
    // do nothing
  }
};
```

It will add the property name into function, hows it happened? did i set up a wrong setting?

**Comment by sebmck** [comment]
No, this is expected behaviour.

**Comment by benji0818** [comment]
omg! i'm sorry for that. Is there any references that I can get through this problem? cause Browser always cause me a error log.

**Comment by sebmck** [comment]
@benji0818 What are error are you getting?
