### ISSUE TITLE
It exceeds the max of "100KB"

### ISSUE THREAD

**Issue by monolithed** [babel/babelify#62]
```
➜ grunt browserify
Running "browserify" (browserify) task

Note: The code generator has deoptimised the styling of "index.js" as it exceeds the max of "100KB".
```

The `babelify` used as transformation for  `grunt-browserify`

```
options: {
	transform: ['babelify']
}
```

How to skip this warning?

**Comment by sebmck** [comment]
```javascript
options: {
    transform: [['babelify', { compact: false }]]
}
```

Probably not a good idea to be passing such large files through Babel in the first place.

**Comment by monolithed** [comment]
@sebmck, more thanks!

**Comment by btburton42** [comment]
Is there a recommended pattern for when you must import a utility library like `lodash` into one of your babel components?

**Comment by sebmck** [comment]
@btburton42 Don't let browserify transform it since there's no reason to let it.

**Comment by btburton42** [comment]
Ha, yeah, I just figured that out myself. Thanks!

**Comment by nobleach** [comment]
How would you go about that given your Grunt example above?

**Comment by ppiekarczyk** [comment]
I'm getting this same error with moment in production. Is there anything I can do?

**Comment by sebmck** [comment]
@ppiekarczyk As previously mentioned, set `compact` to `false`.

**Comment by nobleach** [comment]
I should say, I'm not seeing a way to blacklist those larger files. Perhaps this is outside of the scope of babelify?

**Comment by btburton42** [comment]
@nobleach if you're using grunt you can tell it only to pipe certain files to the bebelify grunt task. i don't know if bebelify itself has an ignore command though.

**Comment by nobleach** [comment]
Yeah, I'll have to check Browserify. I'm sure there has to be a way.

**Comment by zertosh** [comment]
@nobleach What is it exactly that you're trying to do?

**Comment by nobleach** [comment]
I am babelifying all required files with the exception of 2 vendor libs which we unwrap and include. One is our handlebars templates and the other is Marionette. I'd like to just ignore those two things.

**Comment by zertosh** [comment]
> I am babelifying all required files with the exception of 2 vendor libs which we unwrap and include.

@nobleach By "unwrap and include" do you mean that you're not requiring them from `node_modules`, but rather they're normal project files? If so, then you can't tell browserify to exclude them from the transforms, but you can tell babel to skip them:

```js
var b = browserify({/*options*/});
b.transform(babelify.configure({
  ignore: ['**/vendor/template-lib.js', '**/vendor/marionette*']
});
b.bundle();
```

Browserify passes the full path of a file to babelify, and babelify (via babel) can ignore files if they match a glob pattern in `ignore`. babelify will pass most [options](https://babeljs.io/docs/usage/options/) directly to babel except a [few](https://github.com/babel/babelify/blob/82eedbf4aad1abeecf681f3f2ab5866645984f57/index.js#L12-L19).

**Comment by nobleach** [comment]
Correct, they're not in `node_modules`. The handlebars templates file is rebuilt from Grunt using a watch task.

I'm using grunt-browserify, so I'll need to figure out how to get this into its config/options. Thanks!

**Comment by yuunusdurmus** [comment]
thank you @kittens 
i use like this:
appBundler.transform("babelify", {compact: false, presets: ["es2015", "react"]})
		.bundle().on('error',gutil.log)
		.pipe(source('main.js'))
		.pipe(gulp.dest('./dist/js/'))
		.pipe(browserSync.stream());

**Comment by buuug7** [comment]
@yuunusdurmus 
can i have a look your whole gulpfile?
my gulpfile is like below,i feel my gulpfile is too fat
`'use stric';
var gulp = require("gulp");
var browserify = require("browserify");
var source = require('vinyl-source-stream');
var buffer = require('vinyl-buffer');
var babelify = require('babelify');
var sourcemaps = require('gulp-sourcemaps');
var uglify = require('gulp-uglify');
var gutil = require('gulp-util');

gulp.task("browserify", function() {
    var b = browserify({
        entries: './public/scripts/tutorial.js',
        debug: true,
        transform: [babelify]
    });
    return b.bundle()
        .pipe(source('app.js'))
        .pipe(buffer())
        .pipe(sourcemaps.init({ loadMaps: true }))
        //.pipe(uglify())
        .on('error', gutil.log)
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('./public/dist/js'));

});


gulp.task("default", ["browserify"]);
`

**Comment by yuunusdurmus** [comment]
@buuug7  absolutely, feeling to me sometimes :)
https://github.com/yuunusdurmus/gulp-compile-es6-with-react

**Comment by buuug7** [comment]
thanks a lot@yuunusdurmus,it was great,i have forked your setting files and will use it on my next project

**Comment by IsuruDilhan** [comment]
In react/redux/webpack/babel build fixed this error by removing script tag type text/babel

`<script type="text/babel" src="/js/bundle.js"></script>`

Into
`<script src="/js/bundle.js"></script>`
