### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by philippotto** [babel/babelify#64]
I'm not sure what the exact reason for this is, but I'm experiencing a very low performance in my incremental build process and narrowed it down to babelify.

I am using browserify in conjunction with watchify, which takes care of caching and only building stuff which really needs rebuilding. Without the babelify transformation, changing a single file (ca. 70 LOC) results in a 80 ms rebuild. With babelify it takes 3000 ms.

When hooking into the transformer and printing out the processed files, I notice that without babelify a simple change of `app.jsx` only results in `index.jsx` being processed.
With babelify a change of `app.jsx` results in `index.jsx`, `app.jsx` and **again** `index.jsx` being processed.

Do you have any idea how this could be resolved?

**Comment by philippotto** [comment]
Ok, I think the reason for the differing "processed files"-output is, that I'm using es6 `import`s which of course aren't interpreted by browserify.

Nevertheless, I think that 3 seconds for a change of a 70 lines-file leaves room for improvement. Maybe one can make use of caching, so that resolving the dependency chain of a changed file is done a lot quicker?

**Comment by sebmck** [comment]
Babel does not do anything about dependency resolution, that's obviously
browserifys job.

On Wednesday, 25 March 2015, Philipp Otto <notifications@github.com> wrote:

> Ok, I think the reason for the differing "processed files"-output is, that
> I'm using es6 imports which of course aren't interpreted by browserify.
>
> Nevertheless, I think that 3 seconds for a change of a 70 lines-file
> leaves room for improvement. Maybe one can make use of caching, so that
> resolving the dependency chain of a changed file is done a lot quicker?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babelify/issues/64#issuecomment-85526232>.
>


-- 
Sebastian McKenzie

**Comment by philippotto** [comment]
I'm absolutely with you! But browserify cannot speed up transformations by caching, since the caching-logic would be transformer-dependent, right?

**Comment by philippotto** [comment]
Giving this a second thought, it should be possible to do the caching transformer-independent. I will write again, after I've investigated further.

**Comment by philippotto** [comment]
I'm sorry for the spamming. After having benchmarked the right parts, I come to the conclusion, that the transformations aren't the bottleneck. I'm not yet sure, what exactly is the reason for the relatively slow build times, but since it is not babelify, I'll close this issue.
Sorry again for this overhasty issue.

**Comment by chenkehxx** [comment]
I have the same problem

**Comment by zertosh** [comment]
@philippotto @chenkehxx, if you open new issues with a repo to a slow project, I'd be more than happy to take a look
