### ISSUE TITLE
ES6-style default arguments not respected

### ISSUE THREAD

**Issue by BHouwens** [babel/babelify#65]
It seems that the transpiler doesn't respect setting defaults for arguments the ES6 way. So here:

    constructor(data, element, type = 'spline'){
		super(data, element);
	}

If another value is given to the `type` argument, it still reverts to `'spline'`. Done the current JS way, however:

    constructor(data, element, type){
		this.type = type || 'spline';
		super(data, element);
	}

Does produce the desired result. This is minor, but I just thought I'd bring it to your attention.

**Comment by sebmck** [comment]
Not sure I completely understand the issue. Regardless, potential issues should be bought up on the main [babel](https://github.com/babel/babel) repo as this is the browserify plugin repo.
