### ISSUE TITLE
Too Long build time with watchify

### ISSUE THREAD

**Issue by darkyen** [babel/babelify#66]
Perhaps when using watchify only the file changed should update ?

```javascript
gulp.task('browserify', function(callback){

	function createBundle(b_config){

		var bundler = browserify(b_config.entry, {
			debug: true,
		});

		if( global.isWatching ){
			// console.log("Uses watchify");
			bundler = watchify(bundler);
			bundler.on('update', bundle);
		}

		bundler.transform(to5);

		var reportFinsihed = function(){
			bundleLogger.end(b_config.outputName);


			if( bundleQueueLen ){
				bundleQueueLen --;

				if( bundleQueueLen === 0 ){
					callback();
				}
			}
		};

		function bundle(){
			// Create a logger when it starts logging
			bundleLogger.start(b_config.outputName);

			return bundler.bundle()
					.on('error', handleErrors)
					.pipe(source(b_config.outputName))
					.pipe(gulp.dest(b_config.dest))
					.on('end', reportFinsihed);
		}

		bundle();
	}

	var bundleQueue = config.bundleConfigs;
	var bundleQueueLen = bundleQueue.length;
	bundleQueue.forEach(createBundle);

});

```

But when doing that, It usually takes 8 - 10 seconds to build. And goes over every single file in the app repo which are unchanged. (Found by running ```DEBUG=babel gulp && gulp browserify``` )

Any suggestions ?

**Comment by sebmck** [comment]
> Perhaps when using watchify only the file changed should update ?

This is the case :)

The [babelify](https://github.com/babel/babelify/blob/master/index.js) source is extremely small and only does what browserify tells it to so whatever issues you're seeing are the result of bad config or from watchify/browserify.
