### ISSUE TITLE
Ignore property not respected in babelify.configure()

### ISSUE THREAD

**Issue by konistehrad** [babel/babelify#67]
In version 6.0.0, the ignore property passed to babelify.configure() is deleted by the time File.prototype.shouldIgnore is executed on vendor, ES5 code. This results in jQuery et al being parsed with babel instead of ignored.

**Comment by sebmck** [comment]
Fixed as of 6.0.2

**Comment by konistehrad** [comment]
You're the best person in the whole wide world. :+1:

**Comment by sebmck** [comment]
:kissing_heart:
