### ISSUE TITLE
Babelify builds node dependencies specified as external files in browserify

### ISSUE THREAD

**Issue by spoike** [babel/babelify#70]
Babelify pulls in all the external dependencies even though the browserify build has them set as external (since I'm building a seperate vendor library). I'm doing it like this (in gulp):

```javascript
gulp.task('scripts:app', function() {
    return gulp.src(['./src/js/app.js', './src/js/background.js', './src/js/browser-action.js'])
        .on('error', gutil.log)
        .pipe(plumber())
        .pipe(transform(function(filename) {
            return browserify({
                    transform: [
                        babelify
                    ]
                })
                .external('react')
                .external('react-router')
                .external('lodash')
                .external('reflux')
                .external('moment')
                // .external a lot of other 3rd party libs
                .require(filename, {entry: true})
                .bundle();
        }))
        .pipe(gulp.dest('./dist/src'));
});
```

Setting `only` option seems to ignore building jsx files and I never got the `ignore` option to work at all. I find it extra strange that babelify is pulling in modules from node_modules, since according to docs babel is supposed to ignore those by default.

**Comment by sebmck** [comment]
Whatever possible issues present are browserify related. `babelify` is extremely simple (see [index.js](https://github.com/babel/babelify/blob/master/index.js) which is only ~50 lines) and just transforms whatever browserify gives it.
