### ISSUE TITLE
Updated to 6.0 - Syntax Error

### ISSUE THREAD

**Issue by dubert** [babel/babelify#71]
Oddly enough, babelify 5.0.x works perfectly fine me.

My set up:

In my gulp.js:
```js
gulp.task('browserify', function() {
  var aliases = aliasify.configure({
    aliases: {
      'config': './config' + config + '.json'
    },
    appliesTo: {
      'includeExtensions': ['.js', '.jsx']
    }
  })
  .require(require.resolve('./src/scripts/index.jsx'), { entry: true })
  .transform(babelify)
  .transform(aliases)
```

I receive this error:
```shell
{ [SyntaxError: /config.json: Unexpected token (2:11) while parsing file: /config.json]
  pos: 13,
  loc: { line: 2, column: 11 },
  raisedAt: 14,
```
Config.json
```json
{
  "API_URL": "http://api....",
}
```

Everything still works fine, it's just throwing errors with a JSON file that is included with aliasify. Ideas?

**Comment by sebmck** [comment]
What's the contents of `config.json`?

**Comment by dubert** [comment]
Updated the comment before I saw your reply. I needed to remove the actual URL for privacy reasons.

**Comment by sebmck** [comment]
Fixed as of babelify 6.0.2, thanks!

**Comment by dubert** [comment]
Wow, thank you for the lightning fix!

**Comment by lfilho** [comment]
I'm getting the same error, but for regular babel/register...

JSON:
``` 
{
    "repo1": "myChannel1",
    "repo2": "myChannel2",
    "docflow": "myChannel1"
}
```

Using "babel": "^5.4.2" and "mocha": "^2.2.5" in package.json

And: `mocha test --recursive --compilers js:babel/register` for running the tests.

Any tips?
