### ISSUE TITLE
Error reporting has changed

### ISSUE THREAD

**Issue by mattdesl** [babel/babelify#72]

**Comment by sebmck** [comment]
What does this mean

**Comment by mattdesl** [comment]
Argh, pushed the enter key and it posted an empty issue.

Anyways.. I've been using errorify to pretty-print syntax errors in the browser, see here: 
https://github.com/mattdesl/budo/blob/master/docs/errors.md

Testing with 5.0.4 prints the error as shown above, very nicely organized with line number etc. Switching to babelify 6.0.2 seems to lose the nice line/number reporting, and just prints the error message.

I'll continue to investigate, just wondering if there's anything obvious that jumps out to you?

**Comment by sebmck** [comment]
The `message` no longer contains the code frame. It's only included in the stack trace and it's available separately via the `codeFrame` property.

**Comment by mattdesl** [comment]
Awesome, thanks. :+1: This is not an issue with babelify then.

**Comment by mattdesl** [comment]
Is there any standard for this? Looks like [syntax-error](https://www.npmjs.com/package/syntax-error) uses `annotated` property.
