### ISSUE TITLE
Unexpected transformation of destructuring assignment

### ISSUE THREAD

**Issue by ipy** [babel/babelify#74]
switch(condition1){
      case 1:
      if(condition2){
        [arr[i-1],arr[i]]=[arr[i],arr[i-1]];
      }
      break;
    }

is transformed to:

    switch (condition1) {
      case 1:
        if (condition2) {
          arr[i - 1] = arr[i];
          arr[i] = arr[i - 1];
        }
        break;
    }

It is unexpected. works well if remove the `switch`  condition:

    if(condition2){
      [arr[i-1],arr[i]]=[arr[i],arr[i-1]];
    }

is transformed to:

    var _slicedToArray = function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } };

    if (condition2) {
      var _temp;

      _temp = [arr[i], arr[i - 1]];

      var _temp2 = _slicedToArray(_temp, 2);

      arr[i - 1] = _temp2[0];
      arr[i] = _temp2[1];
    }

babelify version 6.0.2. The `babel` cli works well.

**Comment by sebmck** [comment]
This is expected behaviour, can you explain how it isn't? This is also the repo for the browserify plugin and issues with the output should be reported on the main [babel](https://github.com/babel/babel) repo.

**Comment by fritx** [comment]
damn.. I met this error msg when I wrote `const [a, b] = (null)`
