### ISSUE TITLE
Failed install : 404 on fetch regenerator

### ISSUE THREAD

**Issue by ki7** [babel/babelify#75]
Hello,
Running npm i --save-dev babelify,
I run into :
npm ERR! fetch failed https://github.com/sebmck/regenerator/archive/block-hoist.tar.gz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

Anyone having the same issue

**Comment by sebmck** [comment]
Fixed.

**Comment by ki7** [comment]
Fastest fix ever. thanks
