### ISSUE TITLE
Freeze package dependencies

### ISSUE THREAD

**Issue by danzajdband** [babel/babelify#76]
Hi! We, at getmango.com, have been using 6to6/Babel for a while. It is a very helpful tool for us. Babel's development is very active and that's good but it has been difficult for us to keep our app up-to-date with babel changes, even for those who are aligning more with ES6 spec. The last one being import statements hoisting for example.

If babelify dependencies can be frozen for each release we can then prepare for adapting to new versions. Can this be posible?

Thanks for the great work!

**Comment by sebmck** [comment]
Use [npm shinkwrap](https://docs.npmjs.com/cli/shrinkwrap).

**Comment by danzajdband** [comment]
thx
