### ISSUE TITLE
Verbose output

### ISSUE THREAD

**Issue by RamIdeas** [babel/babelify#77]
Is there a way to strip out the function definitions that are defined at the top of every file that needs them?

i,e. `_interopRequireDefault`, `_classCallCheck`, `_createClass`, `_get`, `_inherits`, etc...

They just bloat the file size and it seems that these could be declared once and referred to, unless there's something I'm missing.

**Comment by sebmck** [comment]
Enable the optional `runtime` transformer and add `babel-runtime` to your `package.json`.

```sh
$ npm install babel-runtime --save
```

To set the `runtime` option do the following if you're setting it via the `transform` in `package.json`

```javascript
{
  "transform": [["babelify", { "optional": ["runtime"] }]]
}
```

or via the Node API if you're using it directly:

```javascript
browserify().transform(babelify.configure({
  optional: ["runtime"]
}))
```

See the [runtime docs](http://babeljs.io/docs/usage/runtime) for more info.
