### ISSUE TITLE
babelify is not ignoring node_modules

### ISSUE THREAD

**Issue by davidgilbertson** [babel/babelify#79]
Hello, 
I'm getting this message: `[BABEL] Note: The code generator has deoptimised the styling of "g:/web/money-site/node_modules/jquery/dist/jquery.js" as it exceeds the max of "100KB".` When running a gulp task using babelify.

The task is taking 40 seconds, I assume because it's going through node modules; I thought node_modules was ignored by default?

This is my gulp file:
````javascript
var gulp = require('gulp');
var browserify = require('gulp-browserify');
var babelify = require('babelify');
var rename = require('gulp-rename');

//Just trying this configure bit, but it doesn't seem to make a difference
babelify.configure({
    only: /app/
});

gulp.task('js', function() {
    return gulp.src('app/client.js', { read: false })
        .pipe( browserify({ extensions: ['.jsx'], transform: ['babelify'] }) )
        .pipe( rename('main.js') )
        .pipe( gulp.dest('dist/') )
    ;
});
````

Any ideas?

P.S. Sorry if this is the wrong repo.

**Comment by sebmck** [comment]
Browserify is what should be doing the actual ignoring. It's default behaviour to not run the transforms on `node_modules` unless otherwise specified.

**Comment by davidgilbertson** [comment]
Cool, thanks for the quick answer. I'll post over there unless you can point me to a quick fix.

**Comment by sebmck** [comment]
Not sure. Just extremely doubtful it's an issue with babelify since it's just a [very small transform](https://github.com/babel/babelify/blob/master/index.js).
