### ISSUE TITLE
Working with transforms: brfs, glslify, etc

### ISSUE THREAD

**Issue by mattdesl** [babel/babelify#81]
Because of the way babel transforms some of the require statements, it ends up breaking things like brfs, glslify, and other source transforms that need to statically analyze the functions. 

For example:

``` js
import fs from 'fs'
console.log(fs.readFileSync(__dirname+'/README.md', 'utf8'))
```

Gets transformed into:

``` js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }
var _fs = require('fs');
var _fs2 = _interopRequireDefault(_fs);
console.log(_fs2['default'].readFileSync(__dirname + '/README.md', 'utf8'));
```

Any ideas?

**Comment by jmm** [comment]
@mattdesl Maybe it should just be documented here that it will change the `require()` calls and needs to be run after transforms that statically analyze them. Although less convenient than not worrying about the order, can you think of situations where that wouldn't be feasible if the user knows about it?

**Comment by mattdesl** [comment]
OK, it seems like static-module is fine with ES6 so running the transform before babelify does work. If the JS file in question is using anything non-ES6 (like JSX) it would probably not be feasible. 

:+1:

**Comment by mattdesl** [comment]
OK, nevermind. It is not that easy it seems. :disappointed: I don't think static-module supports `import` so `brfs` and similar transforms need to be run after babelify to work.

**Comment by revolunet** [comment]
so no way to use brfs+babelify ?

**Comment by mattdesl** [comment]
It will eventually be possible once static-module can handle ES6 imports. For now you need to 'require' brfs with CommonJS syntax, and run the brfs transform after babelify. 

If you have non standard ES6, like JSX or experimental babel features, it won't work having brfs transform before babelify.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
