### ISSUE TITLE
Using Three with Babel via Browserify and Babelify throws an error

### ISSUE THREAD

**Issue by karlas** [babel/babelify#87]
Using this simple code, and bundling it with Browserify (with no transform) works fine:

```
var THREE = require('three');

var camera = new THREE.PerspectiveCamera(35, 1, 1, 10000);
camera.position.set(3, 0.5, 3);

var directionalLight = new THREE.DirectionalLight(0xffffff, 1);
directionalLight.position = camera.position;

console.log("Ok!");
```

But, applying babelify tranform:

```
browserify script.js -t babelify --outfile bundle.js
```

executing it on browser gives following error on console: 

```
Uncaught TypeError: Cannot assign to read only property 'position' of [object Object]
```

If you inspect the bundle.js with this transform, you can get following transform:

```
var directionalLight = new THREE.DirectionalLight(16777215, 1);
````
so, hex value has been converted to decimal.

Any idea? I'm not pretty sure if it's an issue with Three or with Babel. I posted same issue ion Three's repo : https://github.com/mrdoob/three.js/issues/6599

I created a repo with the code I used: https://github.com/karlas/error-babelify-three

Regards

**Comment by zertosh** [comment]
What you're seeing is a strict mode violation. three.js is [making](https://github.com/mrdoob/three.js/blob/5c7e0df9b100ba40cdcaaf530196290e16c34858/src/core/Object3D.js#L39-L42) `position` non-writable and non-configurable. So it's not the hex to dec conversion but rather the `"use strict"`. You can turn off that transform and your code will work:

```sh
browserify script.js -t [ babelify --blacklist strict ] --outfile bundle.js
```

**Comment by karlas** [comment]
Thx! I close this issue
