### ISSUE TITLE
Loading plugins through node_modules browserify prop

### ISSUE THREAD

**Issue by Gijsjan** [babel/babelify#92]
I have this in my package.json for a module:

    "browserify": {
        "transform": [["babelify", { "plugins": ["object-assign"] }]]
    },
    "devDependencies": {
        "babel-core": "^5.5.8",
        "babel-plugin-object-assign": "^1.1.0",
        "babelify": "^6.1.2"
    }

To develop the module locally I use `npm  link`. Babelify is working on the module, but the plugin not so. Is it supposed to work? I could only find a reference to `optional` in the docs. The option `plugins` is recognized, because when I change it to blabberish, I get a `ReferenceError`.

**Comment by zertosh** [comment]
Yeah - I think reading options from the `package.json` is broken. I'll try to get a fix in soon.

**Comment by zertosh** [comment]
@sebmck I looked into this and it's a problem with babel's `PluginManager` and `util.resolveRelative`. The plugin module resolution is done relative to `process.cwd()` instead of the file being transformed.

Consider:

```
your-project
├── node_modules (1)
│ ├── babelify
│ └── other-project
│   └── node_modules (2)
│     └── babel-plugin-object-assign
└── src
  └── main.js
```

If `other-package` has a package.json similar to the OP's, then babel will try to locate `babel-plugin-object-assign` in `node_modules (1)` instead of `node_modules (2)`.

I was going to submit a PR but my not feeling it for my solution:

```diff
diff --git a/src/babel/transformation/file/plugin-manager.js b/src/babel/transformation/file/plugin-manager.js
index ac0e3128..86fdbbb2 100644
--- a/src/babel/transformation/file/plugin-manager.js
+++ b/src/babel/transformation/file/plugin-manager.js
@@ -49,7 +49,8 @@ export default class PluginManager {
     var match = name.match(/^(.*?):(after|before)$/);
     if (match) [, name, position] = match;
 
-    var loc = util.resolveRelative(`babel-plugin-${name}`) || util.resolveRelative(name);
+    var basedir = this.file && this.file.opts.filename;
+    var loc = util.resolveRelative(`babel-plugin-${name}`, basedir) || util.resolveRelative(name, basedir);
     if (loc) {
       var plugin = require(loc);
       return {
diff --git a/src/babel/util.js b/src/babel/util.js
index 123209e2..a1310a8e 100644
--- a/src/babel/util.js
+++ b/src/babel/util.js
@@ -12,6 +12,7 @@ import isString from "lodash/lang/isString";
 import isRegExp from "lodash/lang/isRegExp";
 import Module from "module";
 import isEmpty from "lodash/lang/isEmpty";
+import object from "./helpers/object";
 import parse from "./helpers/parse";
 import path from "path";
 import has from "lodash/object/has";
@@ -37,15 +38,17 @@ export function resolve(loc: string) {
   }
 }
 
-var relativeMod;
+var relativeMod = object();
 
-export function resolveRelative(loc: string) {
+export function resolveRelative(loc: string, basedir?: string) {
   // we're in the browser, probably
   if (typeof Module === "object") return null;
 
-  if (!relativeMod) {
-    relativeMod = new Module;
-    relativeMod.paths = Module._nodeModulePaths(process.cwd());
+  if (!basedir) basedir = process.cwd();
+
+  if (!relativeMod[basedir]) {
+    relativeMod[basedir] = new Module;
+    relativeMod[basedir].paths = Module._nodeModulePaths(basedir);
   }
 
   try {
```

**Comment by zertosh** [comment]
derp... forgot to `path.dirname(this.file.opts.filename)`

**Comment by sebmck** [comment]
@zertosh 

> I looked into this and it's a problem with babel's `PluginManager` and `util.resolveRelative`. The plugin module resolution is done relative to `process.cwd()` instead of the file being transformed.

Yeah this is expected behaviour, in fact it's even documented:

> Plugins are resolved relative to the current working directory.

http://babeljs.io/docs/advanced/plugins/#usage

**Comment by zertosh** [comment]
Ah cool. I can see how it would get really hairy when you start changing the basedir for resolution, but do you think it makes sense to somehow accommodate for this use case?

**Comment by sebmck** [comment]
Probably not. I don't see how you could while supporting the more common one (relative to cwd).

**Comment by zertosh** [comment]
Thanks @sebmck.

@Gijsjan so to make your setup work, you'll have to install `babel-plugin-object-assign` in `$PWD/node_modules/babel-plugin-object-assign`.

**Comment by jmm** [comment]
Not sure about this case, but word has it that in Babel v6, plugins specified in `.babelrc` will be resolved relative to the `.babelrc`.
