### ISSUE TITLE
Importing/requiring .jsx without an extension does not work

### ISSUE THREAD

**Issue by gmaclennan** [babel/babelify#93]
```js
MyClass = require('./my-class')
import MyClass from './my-class'
```

does not work.

```js
MyClass = require('./my-class.jsx')
import MyClass from './my-class.jsx'
```

Does work.

Am I missing something? I thought it should automatically recognize `.jsx` extensions? My browserify command:

`browserify index.jsx -t babelify -o bundle.js`

**Comment by zertosh** [comment]
You need to use the `--extension=.jsx` browserify flag https://github.com/substack/node-browserify#usage

**Comment by gmaclennan** [comment]
I understand now. I don't think the docs are clear about this. I tried to improve that in #97
