### ISSUE TITLE
UMD support

### ISSUE THREAD

**Issue by timdp** [babel/babelify#98]
I'm trying to produce an UMD build that will (among other things) work with RequireJS. The intended scenario is to provide a single, concatenated JS file that developers can easily `require` on the Web, but which will also just expose itself on the `window` if you load it directly. (At a later stage, I might also use it in Node.)

Basically, in my Gulpfile, I pass `{modules: 'umd'}` to `babelify.configure`. The input file is a simple main script that imports a few modules and exports them again.

In the output file, I see the UMD boilerplate for every module, so the option at least has some effect. However, if I then proceed to `require` the file, it just attempts to download every dependency of the main module individually, which fails since I only have the bundle.

Assuming babelify + UMD is a valid scenario, what's the recommended approach here? Should I somehow involve the RequireJS Optimizer? Should I create a separate AMD build? Do I perhaps need additional browserify transforms?

I did quite a bit of Googling already, but I'm struggling to find the appropriate setup. I apologize if this is already documented somewhere, or if it's a RequireJS question rather than a babelify one.

**Comment by zertosh** [comment]
Are you passing the `standalone` option to browserify?

**Comment by zertosh** [comment]
...in combination with [derequire](https://github.com/calvinmetcalf/derequire)

**Comment by timdp** [comment]
That was easier than I thought. Thanks!

Perhaps some clarification for anyone else trying to accomplish this. You'll want to patch [this snippet](https://github.com/babel/babelify#node) to tweak the browserify setup:

1. Pass the `{standalone: 'my-package-name'}` option to `browserify()`.
2. Add `.plugin(require('browserify-derequire'))` to derequire the code.

That'll give you both `window.myPackageName` and `require(['my-package-name'], function (pkg) {})`.
