### ISSUE TITLE
Update babel to the current version?

### ISSUE THREAD

**Issue by alshain** [babel/babelify#99]
Can you update the babel dependency to a more recent version?

Thanks!

**Comment by jmm** [comment]
@alshain The version floats -- you should be able to just `npm update`.

**Comment by alshain** [comment]
Oh, my mistake, I misinterpreted the `"^5.0.0"` dependency. Sorry!

I thought I was affected by [this bug](https://github.com/babel/babel/issues/1566) and saw that it was fixed in `5.4.4`, I only later noticed that I did something else wrong.

Thanks anyway!

**Comment by jmm** [comment]
No problem!
